# Classifying BBQ product reviews with Jev

A fictional barbecue retailer: customers, their orders over time, and the reviews they chose to write, generated deterministically (see [`docs/data-model.md`](../docs/data-model.md)). Every review sentence is then classified by [TypeSafe AI's Jev](https://docs.typesafe.ai/introduction), a *System One* model that answers typed questions (`Choice`, `Score`, `Noul`) with probabilities and a confidence, instead of generating text to be parsed.

1. Generate customers, orders and reviews, and write the review text.
2. Load the reviews, each with what we knew about the customer **at the moment they wrote it**.
3. Break each review into sentences.
4. Ask Jev about every sentence, with the whole review as context.
5. Roll the answers up into things a product or support team can act on.

All the logic lives in `src/`; this notebook only runs it. `TYPESAFE_API_KEY`, and the Key Vault holding the Azure AI Foundry settings that write review text, are read from `.env`.

In [1]:
from datetime import datetime
from pathlib import Path

import polars as pl
from dotenv import load_dotenv

from jev_classifier import FRUSTRATION_LEVELS, KEY, PROBLEM_CATEGORIES, QUESTION_SET_VERSION, build_questions, classify_sentences, transcript
from retail_generator import add_customers, init_dataset, status
from retail_model import DEFAULT_DIR, read_dataset
from review_insights import cross_mentions, flagged, frustration_by_rating, needs_review, problems_by_product, review_rollup
from review_wrangler import load_reviews, product_catalogue, split_sentences
from review_writer import FoundryReviewWriter

load_dotenv(Path.cwd().parent / ".env")
OUTPUT = Path.cwd().parent / "data" / "output"
pl.Config.set_fmt_str_lengths(90)
pl.Config.set_tbl_rows(25)
pl.Config.set_tbl_width_chars(200)
pl.Config.set_tbl_cols(16);

# The dataset: change these to scale it. The same seed always gives the same data.
CUSTOMERS = 1000
SEED = 42
AS_OF = datetime(2026, 6, 30)

## 1. Generate the dataset

Customers come from Faker, one locale per country. Orders follow `OrderPatterns`: seasonality flipped for the Southern Hemisphere, rare grills, accessories that come with a new grill, fuel matched to the grill and restocked on a cycle. Each purchase has a hidden satisfaction, and people mostly review when they are delighted or unhappy. Review text is written from a brief per review and cached by prompt.

The dataset grows in batches, as the `generate-data` command does (`uv run generate-data --help`). Asking for a `total` is idempotent, so rerunning this notebook reuses what is there. To scale up, raise `CUSTOMERS`, or move time on with `generate-data advance --to <date>`. Each batch reports what it will cost.

In [2]:
init_dataset(DEFAULT_DIR, seed=SEED, as_of=AS_OF)
writer = FoundryReviewWriter.from_env()
report = await add_customers(DEFAULT_DIR, total=CUSTOMERS, writer=writer)
await writer.aclose()
print("\n".join(report.lines() + [""] + status()))

Nothing to do: the dataset already has 1,000 customers.

Dataset at /workspaces/retail-review-knowledge-mining/data/generated: seed 42, 2023-01-01 to 2026-06-30, 1,000 customers, 2 batch(es)
     1  add-customers  2026-09-18T19:45:13  gpt-5.6-terra                    1,000 customers, 8,441 orders, 12,706 order_lines, 1,511 reviews, 1,511 review_truth
     2  fill-texts     2026-09-18T19:54:16  gpt-5.6-terra                    1,511 review_texts

Reviews are a **biased sample** of purchases: only a minority of purchases are reviewed, and the stars lean to the extremes.

In [3]:
tables = read_dataset()
purchases = tables["order_lines"].height
reviewed = tables["reviews"].height
print(f"{reviewed:,} of {purchases:,} purchases reviewed ({reviewed / purchases:.1%})")
tables["reviews"]["rating"].value_counts().sort("rating").with_columns(share=(pl.col("count") / reviewed).round(3))

1,511 of 12,706 purchases reviewed (11.9%)

shape: (5, 3)
┌────────┬───────┬───────┐
│ rating ┆ count ┆ share │
│ ---    ┆ ---   ┆ ---   │
│ i8     ┆ u32   ┆ f64   │
╞════════╪═══════╪═══════╡
│ 1      ┆ 109   ┆ 0.072 │
│ 2      ┆ 185   ┆ 0.122 │
│ 3      ┆ 176   ┆ 0.116 │
│ 4      ┆ 577   ┆ 0.382 │
│ 5      ┆ 464   ┆ 0.307 │
└────────┴───────┴───────┘

## 2. Load the reviews

One row per review, joined to its text, its product and **point-in-time customer features**: tenure, lifetime revenue, orders so far and age, all computed only from what happened before the review was written. `review_key` hashes product + text, so each distinct text is classified once.

In [4]:
reviews = load_reviews()
reviews_df = reviews.collect()
print(reviews_df.shape, "-", reviews_df["review_key"].n_unique(), "distinct texts")
reviews_df.head()

(1511, 19) - 1510 distinct texts

shape: (5, 19)
┌─────────────┬─────────────┬────────────┬────────────┬────────────┬────────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┬────────────┬─────┬────────┬────────────┐
│ review_id   ┆ review_key  ┆ customer_i ┆ product_id ┆ product_na ┆ product_ca ┆ rating ┆ reviewed_a ┆ … ┆ tenure_day ┆ lifetime_r ┆ order_coun ┆ days_since ┆ previous_r ┆ age ┆ gender ┆ country    │
│ ---         ┆ ---         ┆ d          ┆ ---        ┆ me         ┆ tegory     ┆ ---    ┆ t          ┆   ┆ s          ┆ evenue     ┆ t          ┆ _last_orde ┆ eviews     ┆ --- ┆ ---    ┆ ---        │
│ str         ┆ str         ┆ ---        ┆ str        ┆ ---        ┆ ---        ┆ i8     ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ r          ┆ ---        ┆ i32 ┆ str    ┆ str        │
│             ┆             ┆ str        ┆            ┆ str        ┆ str        ┆        ┆ datetime[μ ┆   ┆ f64        ┆ f64        ┆ u32        ┆ ---        ┆ u32        ┆     ┆        ┆            │
│             ┆             ┆            ┆            ┆            ┆            ┆        ┆ s]         ┆   ┆            ┆            ┆            ┆ f64        ┆            ┆     ┆        ┆            │
╞═════════════╪═════════════╪════════════╪════════════╪════════════╪════════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╪════════════╪═════╪════════╪════════════╡
│ R0000001010 ┆ c50423f1d6d ┆ C0000001   ┆ P014       ┆ SmokeRing  ┆ consumable ┆ 4      ┆ 2023-10-30 ┆ … ┆ 229.477118 ┆ 496.8      ┆ 2          ┆ 5.071366   ┆ 1          ┆ 64  ┆ male   ┆ Costa Rica │
│             ┆ 2           ┆            ┆            ┆ Premium    ┆ s          ┆        ┆ 14:48:03.7 ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│             ┆             ┆            ┆            ┆ Lump       ┆            ┆        ┆ 30870      ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│             ┆             ┆            ┆            ┆ Charcoal   ┆            ┆        ┆            ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│ R0000001011 ┆ 2d73023545b ┆ C0000001   ┆ P015       ┆ WoodChips  ┆ consumable ┆ 2      ┆ 2023-10-30 ┆ … ┆ 229.262488 ┆ 496.8      ┆ 2          ┆ 4.856736   ┆ 0          ┆ 64  ┆ male   ┆ Costa Rica │
│             ┆ 7           ┆            ┆            ┆ Hickory    ┆ s          ┆        ┆ 09:38:59.7 ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│             ┆             ┆            ┆            ┆ Smoking    ┆            ┆        ┆ 30870      ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│             ┆             ┆            ┆            ┆ Chips      ┆            ┆        ┆            ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│ R0000001140 ┆ f549fa54414 ┆ C0000001   ┆ P008       ┆ GrillMaste ┆ accessorie ┆ 5      ┆ 2025-10-26 ┆ … ┆ 956.748218 ┆ 1390.14    ┆ 15         ┆ 5.957014   ┆ 2          ┆ 66  ┆ male   ┆ Costa Rica │
│             ┆ 6           ┆            ┆            ┆ r Elite    ┆ s          ┆        ┆ 21:18:26.6 ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│             ┆             ┆            ┆            ┆ Tongs      ┆            ┆        ┆ 15662      ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│ R0000001142 ┆ 63ecd3264df ┆ C0000001   ┆ P016       ┆ FlameStart ┆ consumable ┆ 5      ┆ 2025-11-11 ┆ … ┆ 972.420255 ┆ 1390.14    ┆ 15         ┆ 21.629051  ┆ 3          ┆ 66  ┆ male   ┆ Costa Rica │
│             ┆ 7           ┆            ┆            ┆ er Natural ┆ s          ┆        ┆ 13:26:10.6 ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│             ┆             ┆            ┆            ┆ Fire       ┆            ┆        ┆ 15662      ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│             ┆             ┆            ┆            ┆ Lighter    ┆            ┆        ┆            ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
│ R0000002000 ┆ d35dcd80053 ┆ C0000002   ┆ P017       ┆ SeasonPro  ┆ consumable ┆ 4      ┆ 2023-11-28 ┆ … ┆ 118.510231 ┆ 36.2       ┆ 1          ┆ 15.828391  ┆ 0          ┆ 41  ┆ male   ┆ New        │
│             ┆ d           ┆            ┆            ┆ BBQ Rub    ┆ s          ┆        ┆ 05:21:27.3 ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆ Zealand    │
│             ┆             ┆            ┆            ┆ Collection ┆            ┆        ┆ 75884      ┆   ┆            ┆            ┆            ┆            ┆            ┆     ┆        ┆            │
└─────────────┴─────────────┴────────────┴────────────┴────────────┴────────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┴────────────┴─────┴────────┴────────────┘

A customer's features move with time. Here is the customer with the most reviews: each review sees only the orders placed before it.

In [5]:
busiest = reviews_df.group_by("customer_id").len().sort("len", "customer_id", descending=[True, False])["customer_id"][0]
reviews_df.filter(pl.col("customer_id") == busiest).select(
    "reviewed_at", "product_name", "rating", pl.col("tenure_days").round(), "lifetime_revenue", "order_count", "previous_reviews"
)

shape: (12, 7)
┌────────────────────────────┬───────────────────────────────────┬────────┬─────────────┬──────────────────┬─────────────┬──────────────────┐
│ reviewed_at                ┆ product_name                      ┆ rating ┆ tenure_days ┆ lifetime_revenue ┆ order_count ┆ previous_reviews │
│ ---                        ┆ ---                               ┆ ---    ┆ ---         ┆ ---              ┆ ---         ┆ ---              │
│ datetime[μs]               ┆ str                               ┆ i8     ┆ f64         ┆ f64              ┆ u32         ┆ u32              │
╞════════════════════════════╪═══════════════════════════════════╪════════╪═════════════╪══════════════════╪═════════════╪══════════════════╡
│ 2023-10-29 12:29:47.846    ┆ CleanBurn Pellets                 ┆ 5      ┆ 192.0       ┆ 1343.23          ┆ 5           ┆ 0                │
│ 2023-11-29 14:31:56.460288 ┆ CleanBurn Pellets                 ┆ 5      ┆ 223.0       ┆ 1720.78          ┆ 9           ┆ 1                │
│ 2024-02-27 14:19:13.116413 ┆ FlameStarter Natural Fire Lighter ┆ 1      ┆ 313.0       ┆ 1887.33          ┆ 11          ┆ 2                │
│ 2024-04-27 14:14:11.506055 ┆ SmokeRing Premium Lump Charcoal   ┆ 4      ┆ 373.0       ┆ 2091.68          ┆ 14          ┆ 3                │
│ 2024-06-12 08:04:05.769885 ┆ SmokeRing Premium Lump Charcoal   ┆ 4      ┆ 419.0       ┆ 2176.16          ┆ 15          ┆ 4                │
│ 2024-10-14 17:50:05.999772 ┆ CleanBurn Pellets                 ┆ 5      ┆ 543.0       ┆ 2320.66          ┆ 17          ┆ 5                │
│ 2024-11-14 11:23:33.406340 ┆ CleanBurn Pellets                 ┆ 5      ┆ 574.0       ┆ 2454.83          ┆ 18          ┆ 6                │
│ 2025-04-26 20:20:02.765150 ┆ CleanBurn Pellets                 ┆ 5      ┆ 737.0       ┆ 2720.77          ┆ 21          ┆ 7                │
│ 2026-01-22 02:10:42.680895 ┆ WoodChips Hickory Smoking Chips   ┆ 2      ┆ 1007.0      ┆ 3279.13          ┆ 27          ┆ 8                │
│ 2026-05-13 22:05:11.287032 ┆ CleanBurn Pellets                 ┆ 4      ┆ 1119.0      ┆ 4216.69          ┆ 34          ┆ 9                │
│ 2026-06-16 16:11:17.052905 ┆ SmokeRing Premium Lump Charcoal   ┆ 3      ┆ 1153.0      ┆ 4455.05          ┆ 36          ┆ 10               │
│ 2026-06-26 02:17:10.387245 ┆ CleanBurn Pellets                 ┆ 4      ┆ 1162.0      ┆ 4557.47          ┆ 37          ┆ 11               │
└────────────────────────────┴───────────────────────────────────┴────────┴─────────────┴──────────────────┴─────────────┴──────────────────┘

The **master product list**, the options Jev picks mentions from:

In [6]:
catalogue = product_catalogue()
catalogue

shape: (17, 2)
┌────────────────────────────────────────┬──────────────────┐
│ product_name                           ┆ product_category │
│ ---                                    ┆ ---              │
│ str                                    ┆ str              │
╞════════════════════════════════════════╪══════════════════╡
│ ChefsPride Stainless Steel Spatula Set ┆ accessories      │
│ FlipMaster Long Handle Fork            ┆ accessories      │
│ GrillGuard Heat Resistant Gloves       ┆ accessories      │
│ GrillMaster Elite Tongs                ┆ accessories      │
│ HeatShield Premium Grill Cover         ┆ accessories      │
│ TempCheck Digital Thermometer          ┆ accessories      │
│ CleanBurn Pellets                      ┆ consumables      │
│ FlameStarter Natural Fire Lighter      ┆ consumables      │
│ SeasonPro BBQ Rub Collection           ┆ consumables      │
│ SmokeRing Premium Lump Charcoal        ┆ consumables      │
│ WoodChips Hickory Smoking Chips        ┆ consumables      │
│ BBQ Baron Pellet Smoker                ┆ grills           │
│ BackYard King Compact Grill            ┆ grills           │
│ FireMaster Pro 3000 Gas Grill          ┆ grills           │
│ FlameForge Electric Indoor Grill       ┆ grills           │
│ SmokeChief Deluxe Charcoal Kettle      ┆ grills           │
│ TurboGrill Portable Gas                ┆ grills           │
└────────────────────────────────────────┴──────────────────┘

## 3. Break reviews into sentences

In [7]:
sentences = split_sentences(reviews).collect()
print(f"{sentences.height} sentences, {sentences.select(KEY).n_unique()} distinct to classify")
sentences.select("review_id", "product_name", "sentence_index", "sentence_count", "sentence").head(12)

6781 sentences, 6779 distinct to classify

shape: (12, 5)
┌─────────────┬───────────────────────────────────┬────────────────┬────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┐
│ review_id   ┆ product_name                      ┆ sentence_index ┆ sentence_count ┆ sentence                                                                                    │
│ ---         ┆ ---                               ┆ ---            ┆ ---            ┆ ---                                                                                         │
│ str         ┆ str                               ┆ u32            ┆ u32            ┆ str                                                                                         │
╞═════════════╪═══════════════════════════════════╪════════════════╪════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╡
│ R0000001010 ┆ SmokeRing Premium Lump Charcoal   ┆ 0              ┆ 3              ┆ Por el precio, esta bolsa de 20 lb rinde muchísimo más de lo que esperaba; los trozos vien… │
│ R0000001010 ┆ SmokeRing Premium Lump Charcoal   ┆ 1              ┆ 3              ┆ La usé en dos parrilladas largas y todavía me queda suficiente para otra, así que sale mej… │
│ R0000001010 ┆ SmokeRing Premium Lump Charcoal   ┆ 2              ┆ 3              ┆ Le quito una estrella porque encontré algo de polvo al fondo de la bolsa, pero la recomien… │
│ R0000001011 ┆ WoodChips Hickory Smoking Chips   ┆ 0              ┆ 2              ┆ Las virutas tardaron muchísimo en empezar a humear y luego se consumieron demasiado rápido… │
│ R0000001011 ┆ WoodChips Hickory Smoking Chips   ┆ 1              ┆ 2              ┆ Apenas dieron sabor a hickory a las costillas y tuve que añadir bastante más de lo esperad… │
│ R0000001140 ┆ GrillMaster Elite Tongs           ┆ 0              ┆ 4              ┆ Se sienten muy sólidos y bien hechos, nada que ver con los típicos pinchos endebles que se… │
│ R0000001140 ┆ GrillMaster Elite Tongs           ┆ 1              ┆ 4              ┆ El acero es grueso, el mecanismo de bloqueo funciona suave y las puntas agarran muy bien i… │
│ R0000001140 ┆ GrillMaster Elite Tongs           ┆ 2              ┆ 4              ┆ Las empuñaduras no se calientan y después de varias parrilladas siguen como nuevas.         │
│ R0000001140 ┆ GrillMaster Elite Tongs           ┆ 3              ┆ 4              ┆ Los recomiendo totalmente por su calidad y comodidad.                                       │
│ R0000001142 ┆ FlameStarter Natural Fire Lighter ┆ 0              ┆ 2              ┆ These light first time with one match and get the charcoal going quickly without any nasty… │
│ R0000001142 ┆ FlameStarter Natural Fire Lighter ┆ 1              ┆ 2              ┆ Much easier than messing around with paper or lighter fluid, and I’ll definitely be buying… │
│ R0000002000 ┆ SeasonPro BBQ Rub Collection      ┆ 0              ┆ 6              ┆ Used the Memphis Sweet on ribs and the Carolina Tang on pulled pork, and both gave the mea… │
└─────────────┴───────────────────────────────────┴────────────────┴────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┘

## 4. Ask Jev about every sentence

Each call sends one sentence **plus the whole review** as JSON state, and asks 26 questions at once - Jev evaluates them in parallel, so extra questions barely cost latency.

| Question | Type | Why |
|---|---|---|
| `frustration` | Score, 5 levels | How frustrated is the customer? A continuous 0-4. |
| `problem_category` | Choice | Product quality, shipping, ease of use... or `none`. |
| `mentions__<product>` × 17 | Noul each | Which catalogue products the sentence refers to. One Noul per product, because a sentence can mention several. |
| `language` | Choice | Which common language it is written in. |
| `sentiment` | Choice | positive / negative / mixed / neutral. |
| `recommendation` | Choice | Recommends / warns others off / neither. |
| `churn_risk` | Noul | Returning it, refund, switching brand, won't buy again. |
| `safety_concern` | Noul | Burns, fire, gas, unsafe food - an escalation trigger. |
| `suggestion` | Noul | An explicit product improvement idea. |
| `competitor_mention` | Noul | Mentions a product outside our range. |

The star rating and demographics are deliberately **not** sent - see the sanity check below. Answers are cached in `data/output/`, so re-running only pays for new sentences.

In [8]:
questions = build_questions(catalogue.to_dicts())
print(len(questions), "questions per sentence; question set", QUESTION_SET_VERSION)
print("frustration rubric:", *[f"  {i}: {level}" for i, level in enumerate(FRUSTRATION_LEVELS)], sep="\n")

26 questions per sentence; question set 2026-09-18.3
frustration rubric:
  0: Not frustrated: positive, neutral or purely factual.
  1: Mild: a minor gripe or slight disappointment, said calmly.
  2: Clearly frustrated: annoyed or let down by a real problem.
  3: Very frustrated: angry, feels cheated, or the problem ruined the experience.
  4: Furious: hostile or emphatic language, demands a refund, or vows never to buy again.

In [9]:
answers = await classify_sentences(sentences, catalogue, cache_path=OUTPUT / "jev_sentence_answers.parquet")

answers.select(
    pl.col("jev_model").unique().alias("model"),
    pl.col("latency_ms").mean().round().alias("mean_latency_ms"),
    pl.col("input_tokens").sum().alias("input_tokens"),
    pl.col("error").is_not_null().sum().alias("errors"),
)

332 sentence(s) to classify, 7140 cached.

Classified 332 in 19.3s; 0 failed.

shape: (1, 4)
┌────────────┬─────────────────┬──────────────┬────────┐
│ model      ┆ mean_latency_ms ┆ input_tokens ┆ errors │
│ ---        ┆ ---             ┆ ---          ┆ ---    │
│ str        ┆ f64             ┆ i64          ┆ u32    │
╞════════════╪═════════════════╪══════════════╪════════╡
│ jev-1.13.0 ┆ 338.0           ┆ 21280938     ┆ 0      │
└────────────┴─────────────────┴──────────────┴────────┘

### Watch the wire

`transcript.log_to_stdout()` prints every exchange with Jev as JSON: the request body exactly as the SDK sent it (state, model alias, questions) and the response body exactly as the API returned it (the versioned model, every answer with its full probability distribution, token usage), plus the request ID and latency. The question set is printed in full once and elided after that - pass `full_questions=True` to see it every time. The API key travels in a header and is never printed.

The run above came from the cache, so this asks about two sentences afresh. To watch the whole run instead, call `transcript.log_to_stdout()` before it and delete `data/output/jev_sentence_answers.parquet`.

In [10]:
transcript.log_to_stdout()
await classify_sentences(sentences.head(2), catalogue)  # no cache_path, so these always call the API
transcript.silence()

2 sentence(s) to classify, 0 cached.

{
  "at": "2026-09-18T20:30:49.549+00:00",
  "sentence": {"review_key": "c50423f1d6d2", "sentence_index": 1},
  "request_id": "req_01a0b636f2d274e38a5f506f5e833597",
  "latency_ms": 731,
  "sent": {
    "state": {
      "task": "Classify one sentence from a customer review of a barbecue product.",
      "note": "Judge what the sentence itself says. The full review is context for resolving what 'it' or 'this' refers to.",
      "sentence": "La usé en dos parrilladas largas y todavía me queda suficiente para otra, así que sale mejor que varias marcas más caras.",
      "sentence_position": "2 of 3",
      "review": {
        "product_reviewed": "SmokeRing Premium Lump Charcoal",
        "product_category": "consumables",
        "full_text": "Por el precio, esta bolsa de 20 lb rinde muchísimo más de lo que esperaba; los trozos vienen bastante grandes y prende rápido sin dejar sabores raros en la carne. La usé en dos parrilladas largas y todavía me queda suficiente para otra, así que sale mejor que varias marcas más caras. Le quito una estrella porque encontré algo de polvo al fondo de la bolsa, pero la recomiendo totalmente."
      }
    },
    "model": "jev-latest",
    "questions": {
      "frustration": {
        "type": "score",
        "instructions": "How frustrated is the customer in this sentence? Judge the sentence, using the review only to resolve what it refers to.",
        "criteria": ["Not frustrated: positive, neutral or purely factual.", "Mild: a minor gripe or slight disappointment, said calmly.", "Clearly frustrated: annoyed or let down by a real problem.", "Very frustrated: angry, feels cheated, or the problem ruined the experience.", "Furious: hostile or emphatic language, demands a refund, or vows never to buy again."]
      },
      "problem_category": {
        "type": "choice",
        "instructions": "What kind of problem does this sentence raise? Choose 'none' if it raises no problem.",
        "criteria": {
          "none": "No problem is raised: praise, a neutral fact, or a recommendation.",
          "build_quality": "Durability or materials: breaks, bends, rusts, chips, feels cheap, wears out.",
          "performance": "Does not do its job well: heat, temperature control, accuracy, burn, flavour, results.",
          "ease_of_use": "Awkward, fiddly or confusing to use day to day.",
          "assembly": "Hard to assemble, poor instructions, missing or misfitting parts at setup.",
          "cleaning_maintenance": "Hard to clean, ash or grease handling, upkeep.",
          "size_capacity": "Too big, too small, too short, not enough capacity, does not fit.",
          "safety": "A risk of injury, burns, fire, gas leaks or unsafe food.",
          "shipping_delivery": "Late, lost or damaged in transit, wrong item delivered.",
          "customer_service": "Support, returns, warranty or refund handling.",
          "price_value": "Poor value for money, overpriced.",
          "general_dissatisfaction": "Overall disappointment with no specific cause named ('worst grill ever', 'a disaster').",
          "other": "A problem that fits none of the other categories."
        }
      },
      "language": {
        "type": "choice",
        "instructions": "What language is the sentence written in?",
        "criteria": {
          "english": null,
          "spanish": null,
          "portuguese": null,
          "french": null,
          "german": null,
          "italian": null,
          "dutch": null,
          "swahili": null,
          "afrikaans": null,
          "chinese": null,
          "japanese": null,
          "korean": null,
          "hindi": null,
          "arabic": null,
          "russian": null,
          "other": null
        }
      },
      "sentiment": {
        "type": "choice",
        "instructions": "What is the sentiment of this sentence?",
        "criteria": {
          "positive": "Favourable about the product or experience.",
          "negative": "Unfavourable about the product or experience.",
          "mixed": "Both favourable and unfavourable in the same sentence.",
          "neutral": "Factual or descriptive with no clear opinion."
        }
      },
      "recommendation": {
        "type": "choice",
        "instructions": "Does this sentence itself tell others to buy the product, or tell them not to? A complaint on its own is not a warning.",
        "criteria": {
          "recommends": "Recommends the product to others or says it is worth buying.",
          "warns_against": "Tells others not to buy it or to look elsewhere.",
          "none": "Makes no recommendation either way."
        }
      },
      "churn_risk": {
        "type": "noul",
        "instructions": "Does this sentence itself say the customer is returning it, wants a refund, is switching to another brand or going back to their old one, or will not buy again? Answer from this sentence alone, not from the rest of the review."
      },
      "safety_concern": {
        "type": "noul",
        "instructions": "Does this sentence describe a safety risk: injury, burns, fire, a gas leak, or food left unsafe to eat?"
      },
      "suggestion": {
        "type": "noul",
        "instructions": "Does this sentence explicitly suggest or wish for a specific change to the product (e.g. 'the cord could be longer', 'wish it came in more colours')? Describing a fault is not a suggestion."
      },
      "competitor_mention": {
        "type": "noul",
        "instructions": "Does this sentence mention a product that is not in our range - a competitor, another brand, or a product the customer used before? Our range is: ChefsPride Stainless Steel Spatula Set; FlipMaster Long Handle Fork; GrillGuard Heat Resistant Gloves; GrillMaster Elite Tongs; HeatShield Premium Grill Cover; TempCheck Digital Thermometer; CleanBurn Pellets; FlameStarter Natural Fire Lighter; SeasonPro BBQ Rub Collection; SmokeRing Premium Lump Charcoal; WoodChips Hickory Smoking Chips; BBQ Baron Pellet Smoker; BackYard King Compact Grill; FireMaster Pro 3000 Gas Grill; FlameForge Electric Indoor Grill; SmokeChief Deluxe Charcoal Kettle; TurboGrill Portable Gas."
      },
      "mentions__chefspride_stainless_steel_spatula_set": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the ChefsPride Stainless Steel Spatula Set (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__flipmaster_long_handle_fork": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the FlipMaster Long Handle Fork (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__grillguard_heat_resistant_gloves": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the GrillGuard Heat Resistant Gloves (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__grillmaster_elite_tongs": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the GrillMaster Elite Tongs (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__heatshield_premium_grill_cover": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the HeatShield Premium Grill Cover (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__tempcheck_digital_thermometer": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the TempCheck Digital Thermometer (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__cleanburn_pellets": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the CleanBurn Pellets (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__flamestarter_natural_fire_lighter": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the FlameStarter Natural Fire Lighter (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__seasonpro_bbq_rub_collection": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the SeasonPro BBQ Rub Collection (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__smokering_premium_lump_charcoal": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the SmokeRing Premium Lump Charcoal (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__woodchips_hickory_smoking_chips": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the WoodChips Hickory Smoking Chips (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__bbq_baron_pellet_smoker": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the BBQ Baron Pellet Smoker (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__backyard_king_compact_grill": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the BackYard King Compact Grill (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__firemaster_pro_3000_gas_grill": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the FireMaster Pro 3000 Gas Grill (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__flameforge_electric_indoor_grill": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the FlameForge Electric Indoor Grill (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__smokechief_deluxe_charcoal_kettle": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the SmokeChief Deluxe Charcoal Kettle (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__turbogrill_portable_gas": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the TurboGrill Portable Gas (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      }
    }
  },
  "received": {
    "model": "jev-1.13.0",
    "answers": {
      "frustration": {
        "type": "score",
        "score": 0.0,
        "confidence": 1.0,
        "legend": {
          "0": "Not frustrated: positive, neutral or purely factual.",
          "1": "Mild: a minor gripe or slight disappointment, said calmly.",
          "2": "Clearly frustrated: annoyed or let down by a real problem.",
          "3": "Very frustrated: angry, feels cheated, or the problem ruined the experience.",
          "4": "Furious: hostile or emphatic language, demands a refund, or vows never to buy again."
        },
        "probabilities": {"0": 1.0, "1": 0.0, "2": 0.0, "3": 0.0, "4": 0.0}
      },
      "problem_category": {
        "type": "choice",
        "choice": "none",
        "confidence": 0.98,
        "probabilities": {
          "other": 0.0,
          "ease_of_use": 0.0,
          "performance": 0.0,
          "cleaning_maintenance": 0.0,
          "assembly": 0.0,
          "none": 0.98,
          "size_capacity": 0.0,
          "build_quality": 0.0,
          "price_value": 0.02,
          "shipping_delivery": 0.0,
          "customer_service": 0.0,
          "general_dissatisfaction": 0.0,
          "safety": 0.0
        }
      },
      "language": {
        "type": "choice",
        "choice": "spanish",
        "confidence": 0.99,
        "probabilities": {
          "english": 0.0,
          "italian": 0.0,
          "german": 0.0,
          "arabic": 0.0,
          "japanese": 0.0,
          "hindi": 0.0,
          "portuguese": 0.01,
          "other": 0.0,
          "afrikaans": 0.0,
          "korean": 0.0,
          "dutch": 0.0,
          "chinese": 0.0,
          "russian": 0.0,
          "spanish": 0.99,
          "french": 0.0,
          "swahili": 0.0
        }
      },
      "sentiment": {
        "type": "choice",
        "choice": "positive",
        "confidence": 1.0,
        "probabilities": {"neutral": 0.0, "positive": 1.0, "negative": 0.0, "mixed": 0.0}
      },
      "recommendation": {
        "type": "choice",
        "choice": "recommends",
        "confidence": 0.61,
        "probabilities": {"recommends": 0.74, "warns_against": 0.0, "none": 0.26}
      },
      "churn_risk": {"type": "noul", "noul": 0.02},
      "safety_concern": {"type": "noul", "noul": 0.02},
      "suggestion": {"type": "noul", "noul": 0.02},
      "competitor_mention": {"type": "noul", "noul": 0.57},
      "mentions__chefspride_stainless_steel_spatula_set": {"type": "noul", "noul": 0.01},
      "mentions__flipmaster_long_handle_fork": {"type": "noul", "noul": 0.01},
      "mentions__grillguard_heat_resistant_gloves": {"type": "noul", "noul": 0.01},
      "mentions__grillmaster_elite_tongs": {"type": "noul", "noul": 0.01},
      "mentions__heatshield_premium_grill_cover": {"type": "noul", "noul": 0.01},
      "mentions__tempcheck_digital_thermometer": {"type": "noul", "noul": 0.01},
      "mentions__cleanburn_pellets": {"type": "noul", "noul": 0.02},
      "mentions__flamestarter_natural_fire_lighter": {"type": "noul", "noul": 0.01},
      "mentions__seasonpro_bbq_rub_collection": {"type": "noul", "noul": 0.01},
      "mentions__smokering_premium_lump_charcoal": {"type": "noul", "noul": 0.93},
      "mentions__woodchips_hickory_smoking_chips": {"type": "noul", "noul": 0.01},
      "mentions__bbq_baron_pellet_smoker": {"type": "noul", "noul": 0.02},
      "mentions__backyard_king_compact_grill": {"type": "noul", "noul": 0.01},
      "mentions__firemaster_pro_3000_gas_grill": {"type": "noul", "noul": 0.01},
      "mentions__flameforge_electric_indoor_grill": {"type": "noul", "noul": 0.01},
      "mentions__smokechief_deluxe_charcoal_kettle": {"type": "noul", "noul": 0.02},
      "mentions__turbogrill_portable_gas": {"type": "noul", "noul": 0.02}
    },
    "usage": {"input_tokens": 2839, "output_tokens": 908}
  }
}

{
  "at": "2026-09-18T20:30:49.770+00:00",
  "sentence": {"review_key": "c50423f1d6d2", "sentence_index": 0},
  "request_id": "req_01a0b636f3c77ea89c74f00f8a7ef161",
  "latency_ms": 952,
  "sent": {
    "state": {
      "task": "Classify one sentence from a customer review of a barbecue product.",
      "note": "Judge what the sentence itself says. The full review is context for resolving what 'it' or 'this' refers to.",
      "sentence": "Por el precio, esta bolsa de 20 lb rinde muchísimo más de lo que esperaba; los trozos vienen bastante grandes y prende rápido sin dejar sabores raros en la carne.",
      "sentence_position": "1 of 3",
      "review": {
        "product_reviewed": "SmokeRing Premium Lump Charcoal",
        "product_category": "consumables",
        "full_text": "Por el precio, esta bolsa de 20 lb rinde muchísimo más de lo que esperaba; los trozos vienen bastante grandes y prende rápido sin dejar sabores raros en la carne. La usé en dos parrilladas largas y todavía me queda suficiente para otra, así que sale mejor que varias marcas más caras. Le quito una estrella porque encontré algo de polvo al fondo de la bolsa, pero la recomiendo totalmente."
      }
    },
    "model": "jev-latest",
    "questions": "<elided: the same 26 questions as the first exchange>"
  },
  "received": {
    "model": "jev-1.13.0",
    "answers": {
      "frustration": {
        "type": "score",
        "score": 0.0,
        "confidence": 1.0,
        "legend": {
          "0": "Not frustrated: positive, neutral or purely factual.",
          "1": "Mild: a minor gripe or slight disappointment, said calmly.",
          "2": "Clearly frustrated: annoyed or let down by a real problem.",
          "3": "Very frustrated: angry, feels cheated, or the problem ruined the experience.",
          "4": "Furious: hostile or emphatic language, demands a refund, or vows never to buy again."
        },
        "probabilities": {"0": 1.0, "1": 0.0, "2": 0.0, "3": 0.0, "4": 0.0}
      },
      "problem_category": {
        "type": "choice",
        "choice": "none",
        "confidence": 0.99,
        "probabilities": {
          "customer_service": 0.0,
          "shipping_delivery": 0.0,
          "ease_of_use": 0.0,
          "performance": 0.0,
          "none": 0.99,
          "other": 0.0,
          "general_dissatisfaction": 0.0,
          "size_capacity": 0.0,
          "price_value": 0.01,
          "cleaning_maintenance": 0.0,
          "assembly": 0.0,
          "safety": 0.0,
          "build_quality": 0.0
        }
      },
      "language": {
        "type": "choice",
        "choice": "spanish",
        "confidence": 1.0,
        "probabilities": {
          "dutch": 0.0,
          "hindi": 0.0,
          "german": 0.0,
          "afrikaans": 0.0,
          "portuguese": 0.0,
          "russian": 0.0,
          "chinese": 0.0,
          "japanese": 0.0,
          "italian": 0.0,
          "spanish": 1.0,
          "english": 0.0,
          "other": 0.0,
          "french": 0.0,
          "swahili": 0.0,
          "arabic": 0.0,
          "korean": 0.0
        }
      },
      "sentiment": {
        "type": "choice",
        "choice": "positive",
        "confidence": 1.0,
        "probabilities": {"mixed": 0.0, "neutral": 0.0, "negative": 0.0, "positive": 1.0}
      },
      "recommendation": {
        "type": "choice",
        "choice": "none",
        "confidence": 0.28,
        "probabilities": {"recommends": 0.48, "warns_against": 0.0, "none": 0.52}
      },
      "churn_risk": {"type": "noul", "noul": 0.01},
      "safety_concern": {"type": "noul", "noul": 0.03},
      "suggestion": {"type": "noul", "noul": 0.02},
      "competitor_mention": {"type": "noul", "noul": 0.06},
      "mentions__chefspride_stainless_steel_spatula_set": {"type": "noul", "noul": 0.01},
      "mentions__flipmaster_long_handle_fork": {"type": "noul", "noul": 0.01},
      "mentions__grillguard_heat_resistant_gloves": {"type": "noul", "noul": 0.01},
      "mentions__grillmaster_elite_tongs": {"type": "noul", "noul": 0.01},
      "mentions__heatshield_premium_grill_cover": {"type": "noul", "noul": 0.01},
      "mentions__tempcheck_digital_thermometer": {"type": "noul", "noul": 0.01},
      "mentions__cleanburn_pellets": {"type": "noul", "noul": 0.02},
      "mentions__flamestarter_natural_fire_lighter": {"type": "noul", "noul": 0.01},
      "mentions__seasonpro_bbq_rub_collection": {"type": "noul", "noul": 0.01},
      "mentions__smokering_premium_lump_charcoal": {"type": "noul", "noul": 0.95},
      "mentions__woodchips_hickory_smoking_chips": {"type": "noul", "noul": 0.01},
      "mentions__bbq_baron_pellet_smoker": {"type": "noul", "noul": 0.01},
      "mentions__backyard_king_compact_grill": {"type": "noul", "noul": 0.01},
      "mentions__firemaster_pro_3000_gas_grill": {"type": "noul", "noul": 0.01},
      "mentions__flameforge_electric_indoor_grill": {"type": "noul", "noul": 0.01},
      "mentions__smokechief_deluxe_charcoal_kettle": {"type": "noul", "noul": 0.01},
      "mentions__turbogrill_portable_gas": {"type": "noul", "noul": 0.01}
    },
    "usage": {"input_tokens": 2853, "output_tokens": 906}
  }
}

Classified 2 in 1.0s; 0 failed.

Join the answers back onto every sentence (duplicated reviews pick up the same answers) and save the flat result.

In [11]:
classified = sentences.join(answers, on=KEY, how="left")
classified.drop("answers_json").write_parquet(OUTPUT / "sentences_classified.parquet")
classified.select(
    "product_name", "sentence", pl.col("frustration").round(2), "problem_category", "sentiment", "products_mentioned", "language"
).head(15)

shape: (15, 7)
┌───────────────────────────────────┬──────────────────────────────────────────────────────────────────┬─────────────┬──────────────────┬───────────┬───────────────────────────────────────┬──────────┐
│ product_name                      ┆ sentence                                                         ┆ frustration ┆ problem_category ┆ sentiment ┆ products_mentioned                    ┆ language │
│ ---                               ┆ ---                                                              ┆ ---         ┆ ---              ┆ ---       ┆ ---                                   ┆ ---      │
│ str                               ┆ str                                                              ┆ f64         ┆ str              ┆ str       ┆ list[str]                             ┆ str      │
╞═══════════════════════════════════╪══════════════════════════════════════════════════════════════════╪═════════════╪══════════════════╪═══════════╪═══════════════════════════════════════╪══════════╡
│ SmokeRing Premium Lump Charcoal   ┆ Por el precio, esta bolsa de 20 lb rinde muchísimo más de lo que ┆ 0.0         ┆ none             ┆ positive  ┆ ["SmokeRing Premium Lump Charcoal"]   ┆ spanish  │
│                                   ┆ esperaba; los trozos vien…                                       ┆             ┆                  ┆           ┆                                       ┆          │
│ SmokeRing Premium Lump Charcoal   ┆ La usé en dos parrilladas largas y todavía me queda suficiente   ┆ 0.0         ┆ none             ┆ positive  ┆ ["SmokeRing Premium Lump Charcoal"]   ┆ spanish  │
│                                   ┆ para otra, así que sale mej…                                     ┆             ┆                  ┆           ┆                                       ┆          │
│ SmokeRing Premium Lump Charcoal   ┆ Le quito una estrella porque encontré algo de polvo al fondo de  ┆ 0.97        ┆ other            ┆ mixed     ┆ ["SmokeRing Premium Lump Charcoal"]   ┆ spanish  │
│                                   ┆ la bolsa, pero la recomien…                                      ┆             ┆                  ┆           ┆                                       ┆          │
│ WoodChips Hickory Smoking Chips   ┆ Las virutas tardaron muchísimo en empezar a humear y luego se    ┆ 1.99        ┆ performance      ┆ negative  ┆ ["WoodChips Hickory Smoking Chips"]   ┆ spanish  │
│                                   ┆ consumieron demasiado rápido…                                    ┆             ┆                  ┆           ┆                                       ┆          │
│ WoodChips Hickory Smoking Chips   ┆ Apenas dieron sabor a hickory a las costillas y tuve que añadir  ┆ 1.91        ┆ performance      ┆ negative  ┆ ["WoodChips Hickory Smoking Chips"]   ┆ spanish  │
│                                   ┆ bastante más de lo esperad…                                      ┆             ┆                  ┆           ┆                                       ┆          │
│ GrillMaster Elite Tongs           ┆ Se sienten muy sólidos y bien hechos, nada que ver con los       ┆ 0.01        ┆ none             ┆ positive  ┆ ["GrillMaster Elite Tongs"]           ┆ spanish  │
│                                   ┆ típicos pinchos endebles que se…                                 ┆             ┆                  ┆           ┆                                       ┆          │
│ GrillMaster Elite Tongs           ┆ El acero es grueso, el mecanismo de bloqueo funciona suave y las ┆ 0.0         ┆ none             ┆ positive  ┆ ["GrillMaster Elite Tongs"]           ┆ spanish  │
│                                   ┆ puntas agarran muy bien i…                                       ┆             ┆                  ┆           ┆                                       ┆          │
│ GrillMaster Elite Tongs           ┆ Las empuñaduras no se calientan y después de varias parrilladas  ┆ 0.0         ┆ none             ┆ positive  ┆ ["GrillMaster Elite Tongs"]           ┆ spanish  │
│                                   ┆ siguen como nuevas.                                              ┆             ┆                  ┆           ┆                                       ┆          │
│ GrillMaster Elite Tongs           ┆ Los recomiendo totalmente por su calidad y comodidad.            ┆ 0.0         ┆ none             ┆ positive  ┆ ["GrillMaster Elite Tongs"]           ┆ spanish  │
│ FlameStarter Natural Fire Lighter ┆ These light first time with one match and get the charcoal going ┆ 0.0         ┆ none             ┆ positive  ┆ ["FlameStarter Natural Fire Lighter"] ┆ english  │
│                                   ┆ quickly without any nasty…                                       ┆             ┆                  ┆           ┆                                       ┆          │
│ FlameStarter Natural Fire Lighter ┆ Much easier than messing around with paper or lighter fluid, and ┆ 0.0         ┆ none             ┆ positive  ┆ ["FlameStarter Natural Fire Lighter"] ┆ english  │
│                                   ┆ I’ll definitely be buying…                                       ┆             ┆                  ┆           ┆                                       ┆          │
│ SeasonPro BBQ Rub Collection      ┆ Used the Memphis Sweet on ribs and the Carolina Tang on pulled   ┆ 0.0         ┆ none             ┆ positive  ┆ ["SeasonPro BBQ Rub Collection"]      ┆ english  │
│                                   ┆ pork, and both gave the mea…                                     ┆             ┆                  ┆           ┆                                       ┆          │
│ SeasonPro BBQ Rub Collection      ┆ The rubs stuck well during a long cook and formed a nice bark on ┆ 0.0         ┆ none             ┆ positive  ┆ ["SeasonPro BBQ Rub Collection"]      ┆ english  │
│                                   ┆ the ribs.                                                        ┆             ┆                  ┆           ┆                                       ┆          │
│ SeasonPro BBQ Rub Collection      ┆ Carolina Tang had the vinegar-style kick I wanted, while Memphis ┆ 0.0         ┆ none             ┆ positive  ┆ ["SeasonPro BBQ Rub Collection"]      ┆ english  │
│                                   ┆ Sweet was good for the ki…                                       ┆             ┆                  ┆           ┆                                       ┆          │
│ SeasonPro BBQ Rub Collection      ┆ The other blends seem useful, though I have only tried four of   ┆ 0.01        ┆ none             ┆ positive  ┆ ["SeasonPro BBQ Rub Collection"]      ┆ english  │
│                                   ┆ the six so far.                                                  ┆             ┆                  ┆           ┆                                       ┆          │
└───────────────────────────────────┴──────────────────────────────────────────────────────────────────┴─────────────┴──────────────────┴───────────┴───────────────────────────────────────┴──────────┘

## 5. What the answers say

### Sanity check: does frustration track the star rating?

Jev never saw the rating, so if frustration falls as stars rise, it is reading the text rather than the number.

In [12]:
by_review = review_rollup(classified.lazy())
frustration_by_rating(by_review).collect()

shape: (5, 4)
┌────────┬─────────┬──────────────────┬──────────────────┐
│ rating ┆ reviews ┆ peak_frustration ┆ mean_frustration │
│ ---    ┆ ---     ┆ ---              ┆ ---              │
│ i8     ┆ u32     ┆ f64              ┆ f64              │
╞════════╪═════════╪══════════════════╪══════════════════╡
│ 1      ┆ 109     ┆ 2.94             ┆ 2.39             │
│ 2      ┆ 185     ┆ 2.22             ┆ 1.85             │
│ 3      ┆ 176     ┆ 1.35             ┆ 0.87             │
│ 4      ┆ 577     ┆ 0.81             ┆ 0.21             │
│ 5      ┆ 464     ┆ 0.01             ┆ 0.0              │
└────────┴─────────┴──────────────────┴──────────────────┘

### Which problems, for which products

In [13]:
problems = problems_by_product(classified.lazy()).collect()
problems.pivot("problem_category", index="product_name", values="sentences").fill_null(0).sort("product_name")

shape: (17, 13)
┌───────────────────┬─────────────┬─────────────┬───────────────────┬───────────────┬───────────────┬─────────────┬───────┬──────────────────┬────────┬──────────┬──────────────────┬──────────────────┐
│ product_name      ┆ performance ┆ price_value ┆ shipping_delivery ┆ build_quality ┆ size_capacity ┆ ease_of_use ┆ other ┆ cleaning_mainten ┆ safety ┆ assembly ┆ general_dissatis ┆ customer_service │
│ ---               ┆ ---         ┆ ---         ┆ ---               ┆ ---           ┆ ---           ┆ ---         ┆ ---   ┆ ance             ┆ ---    ┆ ---      ┆ faction          ┆ ---              │
│ str               ┆ u32         ┆ u32         ┆ u32               ┆ u32           ┆ u32           ┆ u32         ┆ u32   ┆ ---              ┆ u32    ┆ u32      ┆ ---              ┆ u32              │
│                   ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆ u32              ┆        ┆          ┆ u32              ┆                  │
╞═══════════════════╪═════════════╪═════════════╪═══════════════════╪═══════════════╪═══════════════╪═════════════╪═══════╪══════════════════╪════════╪══════════╪══════════════════╪══════════════════╡
│ BBQ Baron Pellet  ┆ 2           ┆ 4           ┆ 0                 ┆ 1             ┆ 9             ┆ 4           ┆ 0     ┆ 2                ┆ 0      ┆ 1        ┆ 0                ┆ 0                │
│ Smoker            ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ BackYard King     ┆ 38          ┆ 18          ┆ 6                 ┆ 25            ┆ 0             ┆ 7           ┆ 0     ┆ 17               ┆ 7      ┆ 16       ┆ 5                ┆ 11               │
│ Compact Grill     ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ ChefsPride        ┆ 2           ┆ 4           ┆ 0                 ┆ 15            ┆ 14            ┆ 27          ┆ 2     ┆ 1                ┆ 10     ┆ 0        ┆ 0                ┆ 0                │
│ Stainless Steel   ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ Spatula Set       ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ CleanBurn Pellets ┆ 39          ┆ 37          ┆ 13                ┆ 37            ┆ 2             ┆ 35          ┆ 5     ┆ 22               ┆ 0      ┆ 0        ┆ 0                ┆ 0                │
│ FireMaster Pro    ┆ 0           ┆ 0           ┆ 0                 ┆ 0             ┆ 0             ┆ 0           ┆ 0     ┆ 0                ┆ 0      ┆ 3        ┆ 0                ┆ 0                │
│ 3000 Gas Grill    ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ FlameForge        ┆ 11          ┆ 4           ┆ 3                 ┆ 6             ┆ 0             ┆ 7           ┆ 0     ┆ 10               ┆ 2      ┆ 5        ┆ 1                ┆ 1                │
│ Electric Indoor   ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ Grill             ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ FlameStarter      ┆ 60          ┆ 86          ┆ 35                ┆ 46            ┆ 5             ┆ 5           ┆ 1     ┆ 0                ┆ 0      ┆ 0        ┆ 8                ┆ 3                │
│ Natural Fire      ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ Lighter           ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ FlipMaster Long   ┆ 4           ┆ 12          ┆ 0                 ┆ 28            ┆ 18            ┆ 24          ┆ 0     ┆ 1                ┆ 7      ┆ 0        ┆ 0                ┆ 0                │
│ Handle Fork       ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ GrillGuard Heat   ┆ 16          ┆ 18          ┆ 0                 ┆ 35            ┆ 9             ┆ 39          ┆ 0     ┆ 1                ┆ 21     ┆ 0        ┆ 0                ┆ 0                │
│ Resistant Gloves  ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ GrillMaster Elite ┆ 3           ┆ 5           ┆ 0                 ┆ 10            ┆ 2             ┆ 45          ┆ 0     ┆ 0                ┆ 3      ┆ 0        ┆ 0                ┆ 0                │
│ Tongs             ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ HeatShield        ┆ 5           ┆ 13          ┆ 0                 ┆ 14            ┆ 16            ┆ 22          ┆ 0     ┆ 0                ┆ 0      ┆ 0        ┆ 1                ┆ 0                │
│ Premium Grill     ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ Cover             ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ SeasonPro BBQ Rub ┆ 47          ┆ 25          ┆ 17                ┆ 18            ┆ 31            ┆ 18          ┆ 1     ┆ 1                ┆ 0      ┆ 0        ┆ 2                ┆ 0                │
│ Collection        ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ SmokeChief Deluxe ┆ 2           ┆ 0           ┆ 0                 ┆ 4             ┆ 0             ┆ 1           ┆ 0     ┆ 1                ┆ 3      ┆ 3        ┆ 0                ┆ 0                │
│ Charcoal Kettle   ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ SmokeRing Premium ┆ 107         ┆ 115         ┆ 39                ┆ 24            ┆ 45            ┆ 18          ┆ 32    ┆ 14               ┆ 7      ┆ 0        ┆ 3                ┆ 0                │
│ Lump Charcoal     ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ TempCheck Digital ┆ 28          ┆ 10          ┆ 0                 ┆ 19            ┆ 3             ┆ 37          ┆ 1     ┆ 1                ┆ 5      ┆ 2        ┆ 1                ┆ 0                │
│ Thermometer       ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ TurboGrill        ┆ 8           ┆ 5           ┆ 5                 ┆ 12            ┆ 4             ┆ 1           ┆ 0     ┆ 5                ┆ 2      ┆ 6        ┆ 2                ┆ 9                │
│ Portable Gas      ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
│ WoodChips Hickory ┆ 215         ┆ 104         ┆ 78                ┆ 15            ┆ 13            ┆ 7           ┆ 4     ┆ 3                ┆ 2      ┆ 0        ┆ 14               ┆ 5                │
│ Smoking Chips     ┆             ┆             ┆                   ┆               ┆               ┆             ┆       ┆                  ┆        ┆          ┆                  ┆                  │
└───────────────────┴─────────────┴─────────────┴───────────────────┴───────────────┴───────────────┴─────────────┴───────┴──────────────────┴────────┴──────────┴──────────────────┴──────────────────┘

In [14]:
# The most frustrating problem areas, where at least 3 reviews raise them
problems.filter(pl.col("reviews") >= 3).sort("mean_frustration", descending=True).head(10)

shape: (10, 5)
┌─────────────────────────────────┬─────────────────────────┬───────────┬─────────┬──────────────────┐
│ product_name                    ┆ problem_category        ┆ sentences ┆ reviews ┆ mean_frustration │
│ ---                             ┆ ---                     ┆ ---       ┆ ---     ┆ ---              │
│ str                             ┆ str                     ┆ u32       ┆ u32     ┆ f64              │
╞═════════════════════════════════╪═════════════════════════╪═══════════╪═════════╪══════════════════╡
│ WoodChips Hickory Smoking Chips ┆ general_dissatisfaction ┆ 14        ┆ 14      ┆ 3.18             │
│ BackYard King Compact Grill     ┆ price_value             ┆ 18        ┆ 15      ┆ 2.97             │
│ BackYard King Compact Grill     ┆ customer_service        ┆ 11        ┆ 4       ┆ 2.8              │
│ BackYard King Compact Grill     ┆ general_dissatisfaction ┆ 5         ┆ 5       ┆ 2.69             │
│ WoodChips Hickory Smoking Chips ┆ customer_service        ┆ 5         ┆ 5       ┆ 2.68             │
│ TurboGrill Portable Gas         ┆ customer_service        ┆ 9         ┆ 4       ┆ 2.59             │
│ WoodChips Hickory Smoking Chips ┆ price_value             ┆ 104       ┆ 66      ┆ 2.48             │
│ TurboGrill Portable Gas         ┆ price_value             ┆ 5         ┆ 4       ┆ 2.42             │
│ BackYard King Compact Grill     ┆ assembly                ┆ 16        ┆ 6       ┆ 2.31             │
│ BackYard King Compact Grill     ┆ build_quality           ┆ 25        ┆ 16      ┆ 2.3              │
└─────────────────────────────────┴─────────────────────────┴───────────┴─────────┴──────────────────┘

### Language

About a third of customers in non-English-speaking countries write in their own language. `text_language` is the language each review was written in; `language` is what Jev heard, per sentence. Zulu is deliberately not one of Jev's options, so South African reviews in Zulu should come back as `other`.

In [15]:
(
    classified.group_by("text_language", "language")
    .agg(sentences=pl.len(), min_confidence=pl.col("language_confidence").min())
    .sort("text_language", pl.col("sentences"), descending=[False, True])
)

shape: (9, 4)
┌───────────────┬────────────┬───────────┬────────────────┐
│ text_language ┆ language   ┆ sentences ┆ min_confidence │
│ ---           ┆ ---        ┆ ---       ┆ ---            │
│ str           ┆ str        ┆ u32       ┆ f64            │
╞═══════════════╪════════════╪═══════════╪════════════════╡
│ chinese       ┆ chinese    ┆ 210       ┆ 0.91           │
│ english       ┆ english    ┆ 5527      ┆ 1.0            │
│ german        ┆ german     ┆ 158       ┆ 1.0            │
│ japanese      ┆ japanese   ┆ 215       ┆ 0.98           │
│ portuguese    ┆ portuguese ┆ 146       ┆ 0.98           │
│ spanish       ┆ spanish    ┆ 220       ┆ 0.96           │
│ swahili       ┆ swahili    ┆ 136       ┆ 1.0            │
│ zulu          ┆ other      ┆ 167       ┆ 0.53           │
│ zulu          ┆ french     ┆ 2         ┆ 1.0            │
└───────────────┴────────────┴───────────┴────────────────┘

### Products mentioned in reviews of *other* products

Compatibility and bundling signals - e.g. a cover reviewed alongside the grill it fits.

In [16]:
cross_mentions(classified.lazy()).collect()

shape: (10, 3)
┌─────────────────────────────────┬───────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┐
│ product_name                    ┆ also_mentions                     ┆ sentence                                                                                    │
│ ---                             ┆ ---                               ┆ ---                                                                                         │
│ str                             ┆ str                               ┆ str                                                                                         │
╞═════════════════════════════════╪═══════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╡
│ CleanBurn Pellets               ┆ WoodChips Hickory Smoking Chips   ┆ 火付きが良く、煙の出方も安定していて、スペアリブを6時間ほど低温で炊いても温度がほとんどブレ │
│                                 ┆                                   ┆ ませんでした。                                                                              │
│ CleanBurn Pellets               ┆ WoodChips Hickory Smoking Chips   ┆ 20ポンドでこの価格ならかなりお得です。                                                      │
│ CleanBurn Pellets               ┆ WoodChips Hickory Smoking Chips   ┆ 火付きも安定していてヒッコリーの香りもしっかり出るので、リブを3回焼いても大満足でした。     │
│ CleanBurn Pellets               ┆ WoodChips Hickory Smoking Chips   ┆ ヒッコリーの香りはしっかりあるのに苦味や灰っぽさがなく、肉にきれいなスモーキーさが付きます  │
│                                 ┆                                   ┆ 。                                                                                          │
│ CleanBurn Pellets               ┆ WoodChips Hickory Smoking Chips   ┆ ヒッコリーの香りもしっかりしていて、スペアリブを6時間スモークしたら家族に大好評でした。     │
│ CleanBurn Pellets               ┆ WoodChips Hickory Smoking Chips   ┆ ヒッコリーらしいしっかりした香りが出ますが、肉を苦くするような強さではなく、スペアリブやブ  │
│                                 ┆                                   ┆ リスケットにちょうどいいです。                                                              │
│ CleanBurn Pellets               ┆ WoodChips Hickory Smoking Chips   ┆ ヒッコリーの香りも程よく、スペアリブがとてもおいしく仕上がりました。                        │
│ CleanBurn Pellets               ┆ WoodChips Hickory Smoking Chips   ┆ ヒッコリーの香りはしっかり出て、豚肩ロースを6時間ほど燻したときの風味は悪くありませんでした │
│                                 ┆                                   ┆ 。                                                                                          │
│ SmokeRing Premium Lump Charcoal ┆ FlameStarter Natural Fire Lighter ┆ Os pedaços vieram em bom tamanho, com pouca poeira no fundo do saco, e acendem rápido usan… │
│ SmokeRing Premium Lump Charcoal ┆ FlameStarter Natural Fire Lighter ┆ Se enciende muy rápido con dos pastillas naturales y no tuve que pelearme con una montaña … │
└─────────────────────────────────┴───────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┘

### Escalations: safety concerns and churn risk

In [17]:
flagged(classified.lazy(), "safety_concern").collect()

shape: (98, 5)
┌──────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────────┬─────────────┬─────────────┐
│ product_name                     ┆ sentence                                                                                    ┆ safety_concern ┆ occurrences ┆ frustration │
│ ---                              ┆ ---                                                                                         ┆ ---            ┆ ---         ┆ ---         │
│ str                              ┆ str                                                                                         ┆ f64            ┆ u32         ┆ f64         │
╞══════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╪════════════════╪═════════════╪═════════════╡
│ BackYard King Compact Grill      ┆ Grease dripped past the tray and collected underneath the firebox, which is exactly the ki… ┆ 0.98           ┆ 1           ┆ 2.14        │
│ GrillGuard Heat Resistant Gloves ┆ I grabbed a grate for maybe two seconds and felt a sharp burn across my palm even though t… ┆ 0.98           ┆ 1           ┆ 2.06        │
│ BackYard King Compact Grill      ┆ The electronic ignition kept clicking after the burner lit, and once I smelled gas around … ┆ 0.98           ┆ 1           ┆ 2.02        │
│ FlipMaster Long Handle Fork      ┆ One prong slipped out of the meat and sent hot grease splattering onto my wrist.            ┆ 0.98           ┆ 1           ┆ 2.06        │
│ GrillGuard Heat Resistant Gloves ┆ I bought these specifically to keep my hands safe around my smoker, and instead I ended up… ┆ 0.97           ┆ 1           ┆ 2.41        │
│ GrillGuard Heat Resistant Gloves ┆ These gloves are advertised for handling hot grates, but they let heat through far too qui… ┆ 0.96           ┆ 1           ┆ 2.12        │
│ FlipMaster Long Handle Fork      ┆ This fork feels downright unsafe to use around a hot grill.                                 ┆ 0.96           ┆ 1           ┆ 2.23        │
│ BackYard King Compact Grill      ┆ This grill felt unsafe from the first weekend.                                              ┆ 0.96           ┆ 1           ┆ 2.31        │
│ GrillGuard Heat Resistant Gloves ┆ The silicone grip became slippery once it had a little grease on it, and I nearly dropped … ┆ 0.95           ┆ 1           ┆ 2.26        │
│ BackYard King Compact Grill      ┆ The flame on the left side would suddenly flare up through the grate, turning a few burger… ┆ 0.95           ┆ 1           ┆ 2.13        │
│ FlameForge Electric Indoor Grill ┆ Sahani zililegea wakati wa kutumia na mafuta yalivuja pembeni karibu na waya wa umeme—hii … ┆ 0.94           ┆ 1           ┆ 3.02        │
│ TurboGrill Portable Gas          ┆ The push-button ignition worked, but the propane hose connection felt loose and I could sm… ┆ 0.94           ┆ 1           ┆ 1.56        │
│ FlipMaster Long Handle Fork      ┆ For the price, I expected something sturdy, not a tool that could cause a burn or drop din… ┆ 0.93           ┆ 1           ┆ 2.27        │
│ …                                ┆ …                                                                                           ┆ …              ┆ …           ┆ …           │
│ GrillGuard Heat Resistant Gloves ┆ These gloves started coming apart after the second cook.                                    ┆ 0.56           ┆ 1           ┆ 1.69        │
│ SmokeRing Premium Lump Charcoal  ┆ It also produced more sparks when lighting than the lump charcoal I normally buy.           ┆ 0.55           ┆ 1           ┆ 1.04        │
│ GrillGuard Heat Resistant Gloves ┆ Heat protection is good for quick handling, though I would not keep my hand on a cast-iron… ┆ 0.55           ┆ 1           ┆ 0.26        │
│ GrillGuard Heat Resistant Gloves ┆ The silicone coating started peeling after my third cook, which is unacceptable for gloves… ┆ 0.55           ┆ 1           ┆ 2.07        │
│ TurboGrill Portable Gas          ┆ El metal es tan fino que parece una lata, y el botón de encendido dejó de funcionar en la … ┆ 0.54           ┆ 1           ┆ 2.19        │
│ GrillGuard Heat Resistant Gloves ┆ They feel flimsy and poorly stitched, nothing like something meant for high-heat grilling.  ┆ 0.53           ┆ 1           ┆ 2.03        │
│ TempCheck Digital Thermometer    ┆ También he visto lecturas que cambian varios grados sin mover las sondas.                   ┆ 0.53           ┆ 1           ┆ 1.57        │
│ GrillGuard Heat Resistant Gloves ┆ I bought them mainly for moving hot grates and flipping larger cuts of meat, but I never f… ┆ 0.52           ┆ 1           ┆ 1.93        │
│ TempCheck Digital Thermometer    ┆ I also got a couple of alarm notifications late, which made me stop trusting it for expens… ┆ 0.52           ┆ 1           ┆ 2.01        │
│ GrillGuard Heat Resistant Gloves ┆ The silicone coating also has a couple of small cracks near the fingertips already.         ┆ 0.52           ┆ 1           ┆ 1.18        │
│ SmokeRing Premium Lump Charcoal  ┆ It also produced more sparks and ash than the lump charcoal I normally buy.                 ┆ 0.52           ┆ 1           ┆ 1.23        │
│ TurboGrill Portable Gas          ┆ The grill arrived with a damaged regulator and the push-button ignition never worked, but … ┆ 0.51           ┆ 1           ┆ 2.6         │
└──────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────────┴─────────────┴─────────────┘

In [18]:
flagged(classified.lazy(), "churn_risk").collect()

shape: (86, 5)
┌───────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬─────────────┬─────────────┐
│ product_name                      ┆ sentence                                                                                    ┆ churn_risk ┆ occurrences ┆ frustration │
│ ---                               ┆ ---                                                                                         ┆ ---        ┆ ---         ┆ ---         │
│ str                               ┆ str                                                                                         ┆ f64        ┆ u32         ┆ f64         │
╞═══════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╪════════════╪═════════════╪═════════════╡
│ WoodChips Hickory Smoking Chips   ┆ I feel completely ripped off and will not be buying these again.                            ┆ 0.96       ┆ 2           ┆ 3.7         │
│ WoodChips Hickory Smoking Chips   ┆ I will not be buying this brand again.                                                      ┆ 0.96       ┆ 1           ┆ 3.74        │
│ CleanBurn Pellets                 ┆ My smoker kept struggling to maintain temperature because the fines were clogging the hopp… ┆ 0.96       ┆ 1           ┆ 3.04        │
│ WoodChips Hickory Smoking Chips   ┆ Won’t be buying this brand again.                                                           ┆ 0.96       ┆ 1           ┆ 3.33        │
│ SmokeRing Premium Lump Charcoal   ┆ I feel completely cheated and will not be buying this again.                                ┆ 0.96       ┆ 1           ┆ 3.53        │
│ FlameStarter Natural Fire Lighter ┆ I would not buy these again.                                                                ┆ 0.96       ┆ 1           ┆ 2.7         │
│ FlameForge Electric Indoor Grill  ┆ I feel completely cheated for the price and returned it after one miserable weekend.        ┆ 0.96       ┆ 1           ┆ 3.01        │
│ WoodChips Hickory Smoking Chips   ┆ Absolutely disappointed and I will not be buying this brand again.                          ┆ 0.96       ┆ 1           ┆ 3.92        │
│ WoodChips Hickory Smoking Chips   ┆ For the price, I feel completely ripped off and went back to my usual brand.                ┆ 0.96       ┆ 1           ┆ 3.01        │
│ FlipMaster Long Handle Fork       ┆ I’ve used cheaper carving forks that were just as effective, so I wouldn’t buy this again.  ┆ 0.95       ┆ 1           ┆ 1.93        │
│ WoodChips Hickory Smoking Chips   ┆ I’ll use the rest, but I probably won’t buy this brand again.                               ┆ 0.95       ┆ 1           ┆ 1.64        │
│ WoodChips Hickory Smoking Chips   ┆ Feel completely ripped off and won’t be buying this brand again.                            ┆ 0.95       ┆ 1           ┆ 3.81        │
│ FlameStarter Natural Fire Lighter ┆ I’ll go back to the cheaper firelighters from the supermarket.                              ┆ 0.95       ┆ 1           ┆ 1.67        │
│ …                                 ┆ …                                                                                           ┆ …          ┆ …           ┆ …           │
│ WoodChips Hickory Smoking Chips   ┆ I ended up adding chips from another brand halfway through the cook to get any noticeable … ┆ 0.68       ┆ 1           ┆ 1.96        │
│ FlameStarter Natural Fire Lighter ┆ I’ll be looking for a cheaper alternative next time.                                        ┆ 0.67       ┆ 1           ┆ 1.3         │
│ TurboGrill Portable Gas           ┆ I ended up buying another grill locally because this one was useless in the box.            ┆ 0.67       ┆ 1           ┆ 2.83        │
│ FlameStarter Natural Fire Lighter ┆ 价格如果再低一点还能接受，不然下次可能换别的牌子。                                          ┆ 0.61       ┆ 1           ┆ 1.63        │
│ FlameStarter Natural Fire Lighter ┆ I’ll look for a bigger pack or a more reasonably priced alternative next time.              ┆ 0.6        ┆ 1           ┆ 1.09        │
│ WoodChips Hickory Smoking Chips   ┆ I had to add another brand halfway through my ribs just to get any hickory flavour at all.  ┆ 0.58       ┆ 1           ┆ 2.05        │
│ GrillGuard Heat Resistant Gloves  ┆ I had to grab an old pair of oven mitts to finish cooking because I didn’t trust these at … ┆ 0.58       ┆ 1           ┆ 2.21        │
│ WoodChips Hickory Smoking Chips   ┆ 近所のホームセンターよりかなり高かったので、期待して購入しました。                          ┆ 0.54       ┆ 1           ┆ 1.92        │
│ FlameStarter Natural Fire Lighter ┆ They are odourless as advertised, but the value just is not there compared with the cheape… ┆ 0.54       ┆ 1           ┆ 1.73        │
│ TurboGrill Portable Gas           ┆ When they finally approved a return, they sent a label with the wrong address and delayed … ┆ 0.54       ┆ 1           ┆ 2.66        │
│ WoodChips Hickory Smoking Chips   ┆ I’ll probably look for a larger bulk bag elsewhere.                                         ┆ 0.53       ┆ 1           ┆ 1.29        │
│ FlameStarter Natural Fire Lighter ┆ Cheaper supermarket fire lighters have lasted me longer and worked almost as well.          ┆ 0.5        ┆ 1           ┆ 1.3         │
└───────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴─────────────┴─────────────┘

### Free product ideas: explicit suggestions

In [19]:
flagged(classified.lazy(), "suggestion").collect()

shape: (367, 5)
┌────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬─────────────┬─────────────┐
│ product_name                           ┆ sentence                                                                                    ┆ suggestion ┆ occurrences ┆ frustration │
│ ---                                    ┆ ---                                                                                         ┆ ---        ┆ ---         ┆ ---         │
│ str                                    ┆ str                                                                                         ┆ f64        ┆ u32         ┆ f64         │
╞════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╪════════════╪═════════════╪═════════════╡
│ GrillGuard Heat Resistant Gloves       ┆ I just wish the cuffs were a little longer for reaching deeper into the grill.              ┆ 0.98       ┆ 1           ┆ 1.0         │
│ SeasonPro BBQ Rub Collection           ┆ I only wish the Carolina tang rub came in a slightly larger tin, since we went through tha… ┆ 0.98       ┆ 1           ┆ 0.98        │
│ ChefsPride Stainless Steel Spatula Set ┆ I’d definitely recommend the set; I only wish the handles had hanging loops for easier sto… ┆ 0.97       ┆ 1           ┆ 0.97        │
│ FlipMaster Long Handle Fork            ┆ Die Zinken könnten etwas schärfer und minimal weiter auseinander stehen, damit sie besser … ┆ 0.97       ┆ 1           ┆ 0.99        │
│ ChefsPride Stainless Steel Spatula Set ┆ I took off one star because I wish the handles were a little longer for my larger barbecue… ┆ 0.97       ┆ 1           ┆ 1.0         │
│ HeatShield Premium Grill Cover         ┆ 唯一希望是提手位置再明显一点，晚上收盖时会更好找。                                          ┆ 0.97       ┆ 1           ┆ 0.99        │
│ FlameStarter Natural Fire Lighter      ┆ Better packaging and firmer cubes would make these much more reliable.                      ┆ 0.97       ┆ 1           ┆ 1.14        │
│ ChefsPride Stainless Steel Spatula Set ┆ The thin flipper is great for pancakes and eggs, though I wish the handle on that one were… ┆ 0.97       ┆ 1           ┆ 0.99        │
│ FlameStarter Natural Fire Lighter      ┆ Lost one star only because I would prefer slightly larger cubes for bigger charcoal loads.  ┆ 0.97       ┆ 1           ┆ 0.99        │
│ SeasonPro BBQ Rub Collection           ┆ The only reason I gave four stars is that I wish the Carolina bottle were a little larger … ┆ 0.97       ┆ 1           ┆ 0.98        │
│ FlipMaster Long Handle Fork            ┆ Ningependa tu kishikio kiwe na sehemu ya kushika yenye mpira zaidi kwa faraja ya ziada.     ┆ 0.97       ┆ 1           ┆ 0.98        │
│ SeasonPro BBQ Rub Collection           ┆ Took off one star only because I wish the jars were a little bigger.                        ┆ 0.97       ┆ 1           ┆ 1.0         │
│ SeasonPro BBQ Rub Collection           ┆ Einen Stern ziehe ich nur ab, weil ich mir bei dem Set einen kleinen Streueinsatz für jede… ┆ 0.97       ┆ 1           ┆ 1.0         │
│ …                                      ┆ …                                                                                           ┆ …          ┆ …           ┆ …           │
│ FlameStarter Natural Fire Lighter      ┆ Para um churrasco comum funcionam bem, mas esperava mais uniformidade no corte e na duraçã… ┆ 0.54       ┆ 1           ┆ 1.01        │
│ WoodChips Hickory Smoking Chips        ┆ 以后会买更大包装、更便宜的品牌。                                                            ┆ 0.54       ┆ 1           ┆ 1.53        │
│ GrillMaster Elite Tongs                ┆ They are usable and seem sturdy overall, but for the price I expected smoother action and … ┆ 0.54       ┆ 1           ┆ 1.2         │
│ CleanBurn Pellets                      ┆ 这袋20磅的山核桃木颗粒价格比我附近店里同类产品实惠，性价比不错。                            ┆ 0.53       ┆ 1           ┆ 0.0         │
│ ChefsPride Stainless Steel Spatula Set ┆ Benginganikeza izibambo ukubamba okuthe xaxa uma zimanzi, kodwa ngiyajabula kakhulu ngalel… ┆ 0.53       ┆ 1           ┆ 0.74        │
│ SmokeRing Premium Lump Charcoal        ┆ Won’t be buying this again unless the price comes down significantly.                       ┆ 0.53       ┆ 1           ┆ 1.97        │
│ CleanBurn Pellets                      ┆ I’d definitely recommend these, though I’d love to see an occasional multi-bag discount.    ┆ 0.53       ┆ 1           ┆ 0.58        │
│ SmokeRing Premium Lump Charcoal        ┆ That said, for the price, I expected more consistent pieces and a longer burn.              ┆ 0.52       ┆ 1           ┆ 1.4         │
│ FlameStarter Natural Fire Lighter      ┆ The pack could be slightly better value, but they do the job reliably.                      ┆ 0.52       ┆ 1           ┆ 0.98        │
│ WoodChips Hickory Smoking Chips        ┆ I expected cleaner, more uniformly cut hickory chips for the price.                         ┆ 0.52       ┆ 1           ┆ 1.61        │
│ SeasonPro BBQ Rub Collection           ┆ Ni seti inayofaa kujaribu mitindo mbalimbali, lakini kwa bei yake nilitegemea kila kopo li… ┆ 0.5        ┆ 1           ┆ 1.29        │
│ BBQ Baron Pellet Smoker                ┆ Assembly took a little longer than expected because the instructions could be clearer in a… ┆ 0.5        ┆ 1           ┆ 1.0         │
└────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴─────────────┴─────────────┘

### Competitors and previous products

In [20]:
flagged(classified.lazy(), "competitor_mention").collect()

shape: (479, 5)
┌───────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬─────────────┬─────────────┐
│ product_name                      ┆ sentence                                                                                    ┆ competitor_mention ┆ occurrences ┆ frustration │
│ ---                               ┆ ---                                                                                         ┆ ---                ┆ ---         ┆ ---         │
│ str                               ┆ str                                                                                         ┆ f64                ┆ u32         ┆ f64         │
╞═══════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╪════════════════════╪═════════════╪═════════════╡
│ FlameStarter Natural Fire Lighter ┆ I’ll go back to the cheaper firelighters from the supermarket.                              ┆ 0.96               ┆ 1           ┆ 1.67        │
│ GrillGuard Heat Resistant Gloves  ┆ I’ve bought cheaper hardware-store gloves that performed better and lasted longer.          ┆ 0.95               ┆ 1           ┆ 1.95        │
│ FlameStarter Natural Fire Lighter ┆ Cheaper supermarket fire lighters have lasted me longer and worked almost as well.          ┆ 0.95               ┆ 1           ┆ 1.3         │
│ BBQ Baron Pellet Smoker           ┆ The meat probe reads a few degrees off compared with my ThermoPro.                          ┆ 0.95               ┆ 1           ┆ 1.0         │
│ FlameStarter Natural Fire Lighter ┆ Cheaper supermarket fire lighters have lasted longer for me and worked just as reliably.    ┆ 0.95               ┆ 1           ┆ 1.47        │
│ FlameStarter Natural Fire Lighter ┆ I usually needed two or three lighters where one firelighter from my previous brand did th… ┆ 0.94               ┆ 1           ┆ 1.64        │
│ FlameStarter Natural Fire Lighter ┆ Great value for money compared with the supermarket firelighters I was buying before.       ┆ 0.93               ┆ 1           ┆ 0.0         │
│ FlipMaster Long Handle Fork       ┆ It feels sturdier than the cheap fork I picked up at the grocery store last summer.         ┆ 0.93               ┆ 1           ┆ 0.0         │
│ TempCheck Digital Thermometer     ┆ Both probes have given me accurate readings against my old instant-read thermometer.        ┆ 0.93               ┆ 1           ┆ 0.0         │
│ WoodChips Hickory Smoking Chips   ┆ I ended up adding chips from another brand halfway through the cook to get any noticeable … ┆ 0.93               ┆ 1           ┆ 1.96        │
│ GrillGuard Heat Resistant Gloves  ┆ I have used pricier barbecue gloves that were bulkier and less comfortable.                 ┆ 0.92               ┆ 1           ┆ 0.02        │
│ FlameStarter Natural Fire Lighter ┆ Good value for a decent-sized pack, especially compared with the branded fire lighters at … ┆ 0.92               ┆ 1           ┆ 0.0         │
│ FlameStarter Natural Fire Lighter ┆ These are so much easier to use than the old chemical-smelling firelighters I had before.   ┆ 0.92               ┆ 1           ┆ 0.0         │
│ …                                 ┆ …                                                                                           ┆ …                  ┆ …           ┆ …           │
│ SmokeRing Premium Lump Charcoal   ┆ It costs a little more than the basic charcoal at my local store, but the longer burn time… ┆ 0.51               ┆ 1           ┆ 0.11        │
│ CleanBurn Pellets                 ┆ My smoker held temperature well and there was very little ash left after a six-hour cook.   ┆ 0.5                ┆ 1           ┆ 0.0         │
│ CleanBurn Pellets                 ┆ The 20 lb bag lasted me through two long pork shoulder cooks and several weeknight chicken… ┆ 0.5                ┆ 1           ┆ 0.0         │
│ SmokeRing Premium Lump Charcoal   ┆ There were a lot of small pieces and dust at the bottom, so I had to sort through it befor… ┆ 0.5                ┆ 1           ┆ 1.11        │
│ BackYard King Compact Grill       ┆ I had planned to use it for a family cookout and ended up borrowing a neighbor’s grill ins… ┆ 0.5                ┆ 1           ┆ 1.92        │
│ TempCheck Digital Thermometer     ┆ Bei einem 1,8-kg-Nacken vom Smoker konnte ich Garraum und Kerntemperatur gleichzeitig kont… ┆ 0.5                ┆ 1           ┆ 0.0         │
│ CleanBurn Pellets                 ┆ These pellets made my weekend smoke much easier than dealing with wood chunks and constant… ┆ 0.5                ┆ 1           ┆ 0.0         │
│ SmokeRing Premium Lump Charcoal   ┆ I found only a small amount of broken charcoal at the bottom, especially compared with oth… ┆ 0.5                ┆ 1           ┆ 0.01        │
│ SmokeRing Premium Lump Charcoal   ┆ I got nearly three long cooks out of one 20 lb bag, which makes it a better value than the… ┆ 0.5                ┆ 1           ┆ 0.0         │
│ SmokeRing Premium Lump Charcoal   ┆ For a 20 lb bag, I think the price is fair compared with other lump charcoal I’ve bought l… ┆ 0.5                ┆ 1           ┆ 0.0         │
│ FlameStarter Natural Fire Lighter ┆ These are so much easier to use than the old newspaper and kindling routine.                ┆ 0.5                ┆ 1           ┆ 0.0         │
│ SmokeRing Premium Lump Charcoal   ┆ I’d buy it again on sale, but there are cheaper lump options that perform almost as well.   ┆ 0.5                ┆ 1           ┆ 0.94        │
└───────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴─────────────┴─────────────┘

### Low confidence: route to a person

Jev returns a confidence with every Choice. Where it could not separate the problem categories, that is a signal to send the sentence for human review rather than trust the label.

In [21]:
needs_review(classified.lazy(), min_confidence=0.6).collect()

shape: (518, 4)
┌────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────┬─────────────────────────────┐
│ product_name                           ┆ sentence                                                                                    ┆ problem_category     ┆ problem_category_confidence │
│ ---                                    ┆ ---                                                                                         ┆ ---                  ┆ ---                         │
│ str                                    ┆ str                                                                                         ┆ str                  ┆ f64                         │
╞════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════╪═════════════════════════════╡
│ SmokeRing Premium Lump Charcoal        ┆ Once I opened it, I found way too many tiny pieces and crumbs for what is supposed to be p… ┆ build_quality        ┆ 0.2                         │
│ WoodChips Hickory Smoking Chips        ┆ The bag also had far more dust and tiny fragments than usable chips.                        ┆ performance          ┆ 0.2                         │
│ WoodChips Hickory Smoking Chips        ┆ For the price they work well enough, but I would prefer a more consistent chip size.        ┆ performance          ┆ 0.2                         │
│ HeatShield Premium Grill Cover         ┆ Die Passform ist für einen Full-Size-Grill in Ordnung, aber bei Wind würde ich mir zusätzl… ┆ size_capacity        ┆ 0.21                        │
│ SmokeRing Premium Lump Charcoal        ┆ There was a lot more small pieces and dust at the bottom than I expected from a premium lu… ┆ build_quality        ┆ 0.21                        │
│ SmokeRing Premium Lump Charcoal        ┆ There was also more small rubble at the bottom of the bag than I wanted for premium lump.   ┆ price_value          ┆ 0.22                        │
│ SmokeRing Premium Lump Charcoal        ┆ Took off one star because there were a few small bits near the bottom, but overall it does… ┆ other                ┆ 0.23                        │
│ SmokeRing Premium Lump Charcoal        ┆ I knocked off one star because I found a couple of small pieces near the bottom, but I’d d… ┆ size_capacity        ┆ 0.23                        │
│ SmokeRing Premium Lump Charcoal        ┆ What was left inside was mostly undersized pieces and crumbled junk, not premium lump char… ┆ performance          ┆ 0.24                        │
│ WoodChips Hickory Smoking Chips        ┆ There was also a lot of tiny dust and broken pieces at the bottom of the bag, which just f… ┆ build_quality        ┆ 0.24                        │
│ WoodChips Hickory Smoking Chips        ┆ The bag also had a lot of tiny dusty pieces that just fell through the grill grate.         ┆ cleaning_maintenance ┆ 0.24                        │
│ WoodChips Hickory Smoking Chips        ┆ The chips were very inconsistent in size, with a lot of dust and tiny splinters at the bot… ┆ safety               ┆ 0.26                        │
│ SmokeRing Premium Lump Charcoal        ┆ It burned clean and held a steady heat; I only knocked off a star because there was a litt… ┆ cleaning_maintenance ┆ 0.26                        │
│ …                                      ┆ …                                                                                           ┆ …                    ┆ …                           │
│ SmokeRing Premium Lump Charcoal        ┆ I did find a couple of oversized chunks that needed breaking up, but overall the charcoal … ┆ size_capacity        ┆ 0.59                        │
│ WoodChips Hickory Smoking Chips        ┆ Para el precio, esperaba una combustión mucho más constante.                                ┆ performance          ┆ 0.59                        │
│ TempCheck Digital Thermometer          ┆ I would have liked a slightly brighter display on the base unit, otherwise it does the job… ┆ ease_of_use          ┆ 0.59                        │
│ ChefsPride Stainless Steel Spatula Set ┆ The wide turner is so stiff and oversized that it is awkward to slide under burgers withou… ┆ ease_of_use          ┆ 0.59                        │
│ BBQ Baron Pellet Smoker                ┆ It makes good food, but the maintenance is enough of a hassle that I wouldn’t call it a gr… ┆ price_value          ┆ 0.59                        │
│ ChefsPride Stainless Steel Spatula Set ┆ The thin flipper is sharp enough at the edge, yet it flexes too much when lifting anything… ┆ build_quality        ┆ 0.59                        │
│ TempCheck Digital Thermometer          ┆ 通知も分かりやすく便利ですが、たまにBluetoothの接続に少し時間がかかることがあります。       ┆ performance          ┆ 0.59                        │
│ SmokeRing Premium Lump Charcoal        ┆ Le quito una estrella porque encontré algunos pedazos pequeños al fondo de la bolsa, aunqu… ┆ other                ┆ 0.59                        │
│ SmokeChief Deluxe Charcoal Kettle      ┆ The ash catcher is basic but catches most of the mess and makes emptying it less annoying.  ┆ cleaning_maintenance ┆ 0.59                        │
│ FlameForge Electric Indoor Grill       ┆ Ukushisa kuyalungiseka, kodwa ngentengo yalo bengilindele into eqinile nengahlali idlidliz… ┆ price_value          ┆ 0.59                        │
│ FlameStarter Natural Fire Lighter      ┆ 唯一是天气有风的时候最好用两块，起火会更快。                                                ┆ none                 ┆ 0.59                        │
│ FlipMaster Long Handle Fork            ┆ The meat kept slipping when I tried to move it across the grate.                            ┆ performance          ┆ 0.59                        │
└────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────┴─────────────────────────────┘

### Most frustrated reviews

In [22]:
by_review.sort("peak_frustration", descending=True).select(
    "rating", "product_name", pl.col("peak_frustration").round(2), "problems", "churn_risk", "safety_concern", "review_text"
).unique("review_text", maintain_order=True).head(10).collect()

shape: (10, 7)
┌────────┬─────────────────────────────────┬──────────────────┬─────────────────────────────────────────────────────┬────────────┬────────────────┬────────────────────────────────────────────────────┐
│ rating ┆ product_name                    ┆ peak_frustration ┆ problems                                            ┆ churn_risk ┆ safety_concern ┆ review_text                                        │
│ ---    ┆ ---                             ┆ ---              ┆ ---                                                 ┆ ---        ┆ ---            ┆ ---                                                │
│ i8     ┆ str                             ┆ f64              ┆ list[str]                                           ┆ bool       ┆ bool           ┆ str                                                │
╞════════╪═════════════════════════════════╪══════════════════╪═════════════════════════════════════════════════════╪════════════╪════════════════╪════════════════════════════════════════════════════╡
│ 1      ┆ WoodChips Hickory Smoking Chips ┆ 3.97             ┆ ["build_quality", "general_dissatisfaction", …      ┆ true       ┆ false          ┆ 这袋所谓山核桃木屑的品质太差了，打开后里面一半都是 │
│        ┆                                 ┆                  ┆ "shipping_delivery"]                                ┆            ┆                ┆ 粉末和碎渣，根本不像正常的木片。大块木屑又潮又软， │
│        ┆                                 ┆                  ┆                                                     ┆            ┆                ┆ 有几块甚至像是发霉变黑了。放进烟盒没多久就闷灭，只 │
│        ┆                                 ┆                  ┆                                                     ┆            ┆                ┆ 冒出一股刺鼻的焦糊味，完全没有…                    │
│ 1      ┆ WoodChips Hickory Smoking Chips ┆ 3.92             ┆ ["general_dissatisfaction", "performance", …        ┆ true       ┆ false          ┆ The bag was full of tiny crumbs and dust instead   │
│        ┆                                 ┆                  ┆ "shipping_delivery"]                                ┆            ┆                ┆ of proper smoking chips. Nearly half of i…         │
│ 2      ┆ WoodChips Hickory Smoking Chips ┆ 3.91             ┆ ["ease_of_use", "performance", "price_value"]       ┆ true       ┆ false          ┆ ヒッコリーの香りを期待して買ったのに、ほとんど煙が │
│        ┆                                 ┆                  ┆                                                     ┆            ┆                ┆ 出ず風味も全然付きませんでした。説明どおりに水に浸 │
│        ┆                                 ┆                  ┆                                                     ┆            ┆                ┆ してから炭火グリルに入れましたが、すぐに黒く焦げて │
│        ┆                                 ┆                  ┆                                                     ┆            ┆                ┆ 終わりです。少し煙が出たと思っ…                    │
│ 1      ┆ TurboGrill Portable Gas         ┆ 3.9              ┆ ["customer_service", "general_dissatisfaction",     ┆ true       ┆ false          ┆ Paid extra for expedited shipping so I’d have this │
│        ┆                                 ┆                  ┆ "shipping_delivery"]                                ┆            ┆                ┆ grill for a tailgate, and it showed up …           │
│ 2      ┆ WoodChips Hickory Smoking Chips ┆ 3.81             ┆ ["performance", "price_value"]                      ┆ true       ┆ false          ┆ £9.99 for what turned out to be a tiny bag of      │
│        ┆                                 ┆                  ┆                                                     ┆            ┆                ┆ mostly dust and splinters is ridiculous. I g…      │
│ 1      ┆ WoodChips Hickory Smoking Chips ┆ 3.75             ┆ ["customer_service", "general_dissatisfaction", …   ┆ true       ┆ false          ┆ Ngilinde lezi zinkuni ze-hickory amasonto amabili, │
│        ┆                                 ┆                  ┆ "shipping_delivery"]                                ┆            ┆                ┆ nakuba ekhasini bekuthi ukulethwa kuzot…           │
│ 2      ┆ WoodChips Hickory Smoking Chips ┆ 3.74             ┆ ["build_quality", "general_dissatisfaction", …      ┆ true       ┆ false          ┆ Opened the bag and found more dust and tiny        │
│        ┆                                 ┆                  ┆ "shipping_delivery"]                                ┆            ┆                ┆ splinters than usable smoking chips. The piece…    │
│ 1      ┆ WoodChips Hickory Smoking Chips ┆ 3.73             ┆ ["general_dissatisfaction", "performance", …        ┆ true       ┆ false          ┆ Ngikhokhe imali eningi kakhulu ngalesi sikhwama    │
│        ┆                                 ┆                  ┆ "size_capacity"]                                    ┆            ┆                ┆ sama-hickory chips ngilindele ukuthi sizoh…        │
│ 1      ┆ WoodChips Hickory Smoking Chips ┆ 3.73             ┆ ["build_quality", "customer_service", …             ┆ true       ┆ false          ┆ Ordered these hickory chips for a cookout and paid │
│        ┆                                 ┆                  ┆ "shipping_delivery"]                                ┆            ┆                ┆ extra for expedited shipping, but the b…           │
│ 2      ┆ WoodChips Hickory Smoking Chips ┆ 3.7              ┆ ["performance", "price_value", "size_capacity"]     ┆ true       ┆ false          ┆ Absolutely not worth the price they are charging   │
│        ┆                                 ┆                  ┆                                                     ┆            ┆                ┆ for this tiny bag. I expected enough hick…         │
└────────┴─────────────────────────────────┴──────────────────┴─────────────────────────────────────────────────────┴────────────┴────────────────┴────────────────────────────────────────────────────┘