# Classifying BBQ product reviews with Jev

Fictional customer reviews of barbecue products, broken into sentences, with every sentence classified by
[TypeSafe AI's Jev](https://docs.typesafe.ai/introduction) - a *System One* model that answers typed questions
(`Choice`, `Score`, `Noul`) with probabilities and a confidence, instead of generating text to be parsed.

1. Load the raw JSON into a flat Polars frame.
2. Break each review into sentences.
3. Ask Jev about every sentence, with the whole review as context.
4. Roll the answers up into things a product or support team can act on.

All the logic lives in `src/` (`review_wrangler`, `jev_classifier`, `review_insights`); this notebook only runs it.
`TYPESAFE_API_KEY` is read from `.env`.

In [1]:
from pathlib import Path

import polars as pl
from dotenv import load_dotenv

from jev_classifier import FRUSTRATION_LEVELS, KEY, PROBLEM_CATEGORIES, QUESTION_SET_VERSION, build_questions, classify_sentences, transcript
from review_insights import cross_mentions, flagged, frustration_by_rating, needs_review, problems_by_product, review_rollup
from review_wrangler import load_reviews, product_catalogue, split_sentences

load_dotenv(Path.cwd().parent / ".env")
OUTPUT = Path.cwd().parent / "data" / "output"
pl.Config.set_fmt_str_lengths(90)
pl.Config.set_tbl_rows(25)
pl.Config.set_tbl_width_chars(200)
pl.Config.set_tbl_cols(16);

## 1. Load the reviews

One row per review, with the nested `demographics` object flattened into columns. `review_key` hashes product + text: the sample repeats the same text under different customers, and classification is keyed on it so each distinct text is asked about once.

In [2]:
reviews = load_reviews()
reviews_df = reviews.collect()
print(reviews_df.shape, "-", reviews_df["review_key"].n_unique(), "distinct texts")
reviews_df.head()

(256, 11) - 168 distinct texts

shape: (5, 11)
┌────────────┬──────────────┬────────┬────────────────────────────────────┬───────────────────────────────────┬──────────────────┬────────┬─────┬────────────────┬──────────────────┬──────────────────┐
│ review_row ┆ review_key   ┆ rating ┆ review_text                        ┆ product_name                      ┆ product_category ┆ gender ┆ age ┆ country        ┆ days_as_customer ┆ lifetime_revenue │
│ ---        ┆ ---          ┆ ---    ┆ ---                                ┆ ---                               ┆ ---              ┆ ---    ┆ --- ┆ ---            ┆ ---              ┆ ---              │
│ u32        ┆ str          ┆ i64    ┆ str                                ┆ str                               ┆ str              ┆ str    ┆ i64 ┆ str            ┆ i64              ┆ f64              │
╞════════════╪══════════════╪════════╪════════════════════════════════════╪═══════════════════════════════════╪══════════════════╪════════╪═════╪════════════════╪══════════════════╪══════════════════╡
│ 0          ┆ dd3ea70e9f3a ┆ 5      ┆ Absolutely blown away by the       ┆ FireMaster Pro 3000 Gas Grill     ┆ grills           ┆ male   ┆ 45  ┆ United States  ┆ 89               ┆ 1299.99          │
│            ┆              ┆        ┆ FireMaster Pro 3000! Been grilling ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│            ┆              ┆        ┆ for over 20 years and this…        ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│ 1          ┆ 01bf8e70b1ca ┆ 2      ┆ Really disappointed with these     ┆ GrillMaster Elite Tongs           ┆ accessories      ┆ female ┆ 32  ┆ Canada         ┆ 12               ┆ 24.99            │
│            ┆              ┆        ┆ tongs. Handle broke after just 3   ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│            ┆              ┆        ┆ uses. Cheap plastic that c…        ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│ 2          ┆ 737aa10e04fa ┆ 4      ┆ This charcoal lights quickly and   ┆ SmokeRing Premium Lump Charcoal   ┆ consumables      ┆ male   ┆ 38  ┆ Australia      ┆ 184              ┆ 156.47           │
│            ┆              ┆        ┆ burns clean with minimal ash. Good ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│            ┆              ┆        ┆ heat output and lasts …            ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│ 3          ┆ 452620b29c53 ┆ 1      ┆ Total waste of money! This grill   ┆ BackYard King Compact Grill       ┆ grills           ┆ female ┆ 28  ┆ United Kingdom ┆ 21               ┆ 189.99           │
│            ┆              ┆        ┆ arrived with multiple dents and    ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│            ┆              ┆        ┆ scratches, clearly damage…         ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│ 4          ┆ 4b764b6fe747 ┆ 5      ┆ Perfect for quick starts! Lights   ┆ FlameStarter Natural Fire Lighter ┆ consumables      ┆ male   ┆ 52  ┆ Germany        ┆ 412              ┆ 83.45            │
│            ┆              ┆        ┆ charcoal every time without that   ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
│            ┆              ┆        ┆ awful chemical smell oth…          ┆                                   ┆                  ┆        ┆     ┆                ┆                  ┆                  │
└────────────┴──────────────┴────────┴────────────────────────────────────┴───────────────────────────────────┴──────────────────┴────────┴─────┴────────────────┴──────────────────┴──────────────────┘

The **master product list** - the options Jev picks mentions from:

In [3]:
catalogue = product_catalogue(reviews)
catalogue

shape: (17, 2)
┌────────────────────────────────────────┬──────────────────┐
│ product_name                           ┆ product_category │
│ ---                                    ┆ ---              │
│ str                                    ┆ str              │
╞════════════════════════════════════════╪══════════════════╡
│ ChefsPride Stainless Steel Spatula Set ┆ accessories      │
│ FlipMaster Long Handle Fork            ┆ accessories      │
│ GrillGuard Heat Resistant Gloves       ┆ accessories      │
│ GrillMaster Elite Tongs                ┆ accessories      │
│ HeatShield Premium Grill Cover         ┆ accessories      │
│ TempCheck Digital Thermometer          ┆ accessories      │
│ CleanBurn Pellets                      ┆ consumables      │
│ FlameStarter Natural Fire Lighter      ┆ consumables      │
│ SeasonPro BBQ Rub Collection           ┆ consumables      │
│ SmokeRing Premium Lump Charcoal        ┆ consumables      │
│ WoodChips Hickory Smoking Chips        ┆ consumables      │
│ BBQ Baron Pellet Smoker                ┆ grills           │
│ BackYard King Compact Grill            ┆ grills           │
│ FireMaster Pro 3000 Gas Grill          ┆ grills           │
│ FlameForge Electric Indoor Grill       ┆ grills           │
│ SmokeChief Deluxe Charcoal Kettle      ┆ grills           │
│ TurboGrill Portable Gas                ┆ grills           │
└────────────────────────────────────────┴──────────────────┘

## 2. Break reviews into sentences

In [4]:
sentences = split_sentences(reviews).collect()
print(f"{sentences.height} sentences, {sentences.select(KEY).n_unique()} distinct to classify")
sentences.select("review_row", "product_name", "sentence_index", "sentence_count", "sentence").head(12)

1108 sentences, 693 distinct to classify

shape: (12, 5)
┌────────────┬───────────────────────────────┬────────────────┬────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┐
│ review_row ┆ product_name                  ┆ sentence_index ┆ sentence_count ┆ sentence                                                                                    │
│ ---        ┆ ---                           ┆ ---            ┆ ---            ┆ ---                                                                                         │
│ u32        ┆ str                           ┆ u32            ┆ u32            ┆ str                                                                                         │
╞════════════╪═══════════════════════════════╪════════════════╪════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╡
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 0              ┆ 10             ┆ Absolutely blown away by the FireMaster Pro 3000!                                           │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 1              ┆ 10             ┆ Been grilling for over 20 years and this is hands down the best investment I've ever made.  │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 2              ┆ 10             ┆ The temperature control is incredible - holds steady within 5 degrees of your target temp.  │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 3              ┆ 10             ┆ The build quality is outstanding, heavy gauge steel that's going to last decades.           │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 4              ┆ 10             ┆ Assembly was straightforward with clear instructions, took me about 3 hours working at a l… │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 5              ┆ 10             ┆ The cooking space is generous, easily fits 12 burgers or a full rack of ribs with room to … │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 6              ┆ 10             ┆ Heat distribution is perfectly even - no more hot spots burning one side while the other s… │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 7              ┆ 10             ┆ The side burner is powerful enough for serious searing, and the warming rack keeps everyth… │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 8              ┆ 10             ┆ My neighbors are already asking to borrow it!                                               │
│ 0          ┆ FireMaster Pro 3000 Gas Grill ┆ 9              ┆ 10             ┆ Worth every penny and then some.                                                            │
│ 1          ┆ GrillMaster Elite Tongs       ┆ 0              ┆ 4              ┆ Really disappointed with these tongs.                                                       │
│ 1          ┆ GrillMaster Elite Tongs       ┆ 1              ┆ 4              ┆ Handle broke after just 3 uses.                                                             │
└────────────┴───────────────────────────────┴────────────────┴────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┘

## 3. Ask Jev about every sentence

Each call sends one sentence **plus the whole review** as JSON state, and asks 26 questions at once - Jev evaluates them in parallel, so extra questions barely cost latency.

| Question | Type | Why |
|---|---|---|
| `frustration` | Score, 5 levels | How frustrated is the customer? A continuous 0-4. |
| `problem_category` | Choice | Product quality, shipping, ease of use... or `none`. |
| `mentions__<product>` × 17 | Noul each | Which catalogue products the sentence refers to. One Noul per product, because a sentence can mention several. |
| `language` | Choice | Which common language it is written in. |
| `sentiment` | Choice | positive / negative / mixed / neutral. |
| `recommendation` | Choice | Recommends / warns others off / neither. |
| `churn_risk` | Noul | Returning it, refund, switching brand, won't buy again. |
| `safety_concern` | Noul | Burns, fire, gas, unsafe food - an escalation trigger. |
| `suggestion` | Noul | An explicit product improvement idea. |
| `competitor_mention` | Noul | Mentions a product outside our range. |

The star rating and demographics are deliberately **not** sent - see the sanity check below. Answers are cached in `data/output/`, so re-running only pays for new sentences.

In [5]:
questions = build_questions(catalogue.to_dicts())
print(len(questions), "questions per sentence; question set", QUESTION_SET_VERSION)
print("frustration rubric:", *[f"  {i}: {level}" for i, level in enumerate(FRUSTRATION_LEVELS)], sep="\n")

26 questions per sentence; question set 2026-09-18.3
frustration rubric:
  0: Not frustrated: positive, neutral or purely factual.
  1: Mild: a minor gripe or slight disappointment, said calmly.
  2: Clearly frustrated: annoyed or let down by a real problem.
  3: Very frustrated: angry, feels cheated, or the problem ruined the experience.
  4: Furious: hostile or emphatic language, demands a refund, or vows never to buy again.

In [6]:
answers = await classify_sentences(sentences, catalogue, cache_path=OUTPUT / "jev_sentence_answers.parquet")

answers.select(
    pl.col("jev_model").unique().alias("model"),
    pl.col("latency_ms").mean().round().alias("mean_latency_ms"),
    pl.col("input_tokens").sum().alias("input_tokens"),
    pl.col("error").is_not_null().sum().alias("errors"),
)

0 sentence(s) to classify, 693 cached.

shape: (1, 4)
┌────────────┬─────────────────┬──────────────┬────────┐
│ model      ┆ mean_latency_ms ┆ input_tokens ┆ errors │
│ ---        ┆ ---             ┆ ---          ┆ ---    │
│ str        ┆ f64             ┆ i64          ┆ u32    │
╞════════════╪═════════════════╪══════════════╪════════╡
│ jev-1.13.0 ┆ 351.0           ┆ 1925826      ┆ 0      │
└────────────┴─────────────────┴──────────────┴────────┘

### Watch the wire

`transcript.log_to_stdout()` prints every exchange with Jev as JSON: the request body exactly as the SDK sent it (state, model alias, questions) and the response body exactly as the API returned it (the versioned model, every answer with its full probability distribution, token usage), plus the request ID and latency. The question set is printed in full once and elided after that - pass `full_questions=True` to see it every time. The API key travels in a header and is never printed.

The run above came from the cache, so this asks about two sentences afresh. To watch the whole run instead, call `transcript.log_to_stdout()` before it and delete `data/output/jev_sentence_answers.parquet`.

In [7]:
transcript.log_to_stdout()
await classify_sentences(sentences.head(2), catalogue)  # no cache_path, so these always call the API
transcript.silence()

2 sentence(s) to classify, 0 cached.

{
  "at": "2026-09-18T11:59:52.617+00:00",
  "sentence": {"review_key": "dd3ea70e9f3a", "sentence_index": 1},
  "request_id": "req_01a0b4632e4e7b68865f68a25dfa81a8",
  "latency_ms": 594,
  "sent": {
    "state": {
      "task": "Classify one sentence from a customer review of a barbecue product.",
      "note": "Judge what the sentence itself says. The full review is context for resolving what 'it' or 'this' refers to.",
      "sentence": "Been grilling for over 20 years and this is hands down the best investment I've ever made.",
      "sentence_position": "2 of 10",
      "review": {
        "product_reviewed": "FireMaster Pro 3000 Gas Grill",
        "product_category": "grills",
        "full_text": "Absolutely blown away by the FireMaster Pro 3000! Been grilling for over 20 years and this is hands down the best investment I've ever made. The temperature control is incredible - holds steady within 5 degrees of your target temp. The build quality is outstanding, heavy gauge steel that's going to last decades. Assembly was straightforward with clear instructions, took me about 3 hours working at a leisurely pace. The cooking space is generous, easily fits 12 burgers or a full rack of ribs with room to spare. Heat distribution is perfectly even - no more hot spots burning one side while the other stays raw. The side burner is powerful enough for serious searing, and the warming rack keeps everything at the perfect serving temperature. My neighbors are already asking to borrow it! Worth every penny and then some."
      }
    },
    "model": "jev-latest",
    "questions": {
      "frustration": {
        "type": "score",
        "instructions": "How frustrated is the customer in this sentence? Judge the sentence, using the review only to resolve what it refers to.",
        "criteria": ["Not frustrated: positive, neutral or purely factual.", "Mild: a minor gripe or slight disappointment, said calmly.", "Clearly frustrated: annoyed or let down by a real problem.", "Very frustrated: angry, feels cheated, or the problem ruined the experience.", "Furious: hostile or emphatic language, demands a refund, or vows never to buy again."]
      },
      "problem_category": {
        "type": "choice",
        "instructions": "What kind of problem does this sentence raise? Choose 'none' if it raises no problem.",
        "criteria": {
          "none": "No problem is raised: praise, a neutral fact, or a recommendation.",
          "build_quality": "Durability or materials: breaks, bends, rusts, chips, feels cheap, wears out.",
          "performance": "Does not do its job well: heat, temperature control, accuracy, burn, flavour, results.",
          "ease_of_use": "Awkward, fiddly or confusing to use day to day.",
          "assembly": "Hard to assemble, poor instructions, missing or misfitting parts at setup.",
          "cleaning_maintenance": "Hard to clean, ash or grease handling, upkeep.",
          "size_capacity": "Too big, too small, too short, not enough capacity, does not fit.",
          "safety": "A risk of injury, burns, fire, gas leaks or unsafe food.",
          "shipping_delivery": "Late, lost or damaged in transit, wrong item delivered.",
          "customer_service": "Support, returns, warranty or refund handling.",
          "price_value": "Poor value for money, overpriced.",
          "general_dissatisfaction": "Overall disappointment with no specific cause named ('worst grill ever', 'a disaster').",
          "other": "A problem that fits none of the other categories."
        }
      },
      "language": {
        "type": "choice",
        "instructions": "What language is the sentence written in?",
        "criteria": {
          "english": null,
          "spanish": null,
          "portuguese": null,
          "french": null,
          "german": null,
          "italian": null,
          "dutch": null,
          "swahili": null,
          "afrikaans": null,
          "chinese": null,
          "japanese": null,
          "korean": null,
          "hindi": null,
          "arabic": null,
          "russian": null,
          "other": null
        }
      },
      "sentiment": {
        "type": "choice",
        "instructions": "What is the sentiment of this sentence?",
        "criteria": {
          "positive": "Favourable about the product or experience.",
          "negative": "Unfavourable about the product or experience.",
          "mixed": "Both favourable and unfavourable in the same sentence.",
          "neutral": "Factual or descriptive with no clear opinion."
        }
      },
      "recommendation": {
        "type": "choice",
        "instructions": "Does this sentence itself tell others to buy the product, or tell them not to? A complaint on its own is not a warning.",
        "criteria": {
          "recommends": "Recommends the product to others or says it is worth buying.",
          "warns_against": "Tells others not to buy it or to look elsewhere.",
          "none": "Makes no recommendation either way."
        }
      },
      "churn_risk": {
        "type": "noul",
        "instructions": "Does this sentence itself say the customer is returning it, wants a refund, is switching to another brand or going back to their old one, or will not buy again? Answer from this sentence alone, not from the rest of the review."
      },
      "safety_concern": {
        "type": "noul",
        "instructions": "Does this sentence describe a safety risk: injury, burns, fire, a gas leak, or food left unsafe to eat?"
      },
      "suggestion": {
        "type": "noul",
        "instructions": "Does this sentence explicitly suggest or wish for a specific change to the product (e.g. 'the cord could be longer', 'wish it came in more colours')? Describing a fault is not a suggestion."
      },
      "competitor_mention": {
        "type": "noul",
        "instructions": "Does this sentence mention a product that is not in our range - a competitor, another brand, or a product the customer used before? Our range is: ChefsPride Stainless Steel Spatula Set; FlipMaster Long Handle Fork; GrillGuard Heat Resistant Gloves; GrillMaster Elite Tongs; HeatShield Premium Grill Cover; TempCheck Digital Thermometer; CleanBurn Pellets; FlameStarter Natural Fire Lighter; SeasonPro BBQ Rub Collection; SmokeRing Premium Lump Charcoal; WoodChips Hickory Smoking Chips; BBQ Baron Pellet Smoker; BackYard King Compact Grill; FireMaster Pro 3000 Gas Grill; FlameForge Electric Indoor Grill; SmokeChief Deluxe Charcoal Kettle; TurboGrill Portable Gas."
      },
      "mentions__chefspride_stainless_steel_spatula_set": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the ChefsPride Stainless Steel Spatula Set (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__flipmaster_long_handle_fork": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the FlipMaster Long Handle Fork (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__grillguard_heat_resistant_gloves": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the GrillGuard Heat Resistant Gloves (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__grillmaster_elite_tongs": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the GrillMaster Elite Tongs (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__heatshield_premium_grill_cover": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the HeatShield Premium Grill Cover (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__tempcheck_digital_thermometer": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the TempCheck Digital Thermometer (accessories)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__cleanburn_pellets": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the CleanBurn Pellets (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__flamestarter_natural_fire_lighter": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the FlameStarter Natural Fire Lighter (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__seasonpro_bbq_rub_collection": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the SeasonPro BBQ Rub Collection (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__smokering_premium_lump_charcoal": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the SmokeRing Premium Lump Charcoal (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__woodchips_hickory_smoking_chips": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the WoodChips Hickory Smoking Chips (consumables)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__bbq_baron_pellet_smoker": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the BBQ Baron Pellet Smoker (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__backyard_king_compact_grill": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the BackYard King Compact Grill (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__firemaster_pro_3000_gas_grill": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the FireMaster Pro 3000 Gas Grill (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__flameforge_electric_indoor_grill": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the FlameForge Electric Indoor Grill (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__smokechief_deluxe_charcoal_kettle": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the SmokeChief Deluxe Charcoal Kettle (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      },
      "mentions__turbogrill_portable_gas": {
        "type": "noul",
        "instructions": "Does this sentence mention or refer to the TurboGrill Portable Gas (grills)? Yes if it is named, even in passing or by a short name, or if it is what the sentence is describing - including 'it' or 'these' when the review is about it."
      }
    }
  },
  "received": {
    "model": "jev-1.13.0",
    "answers": {
      "frustration": {
        "type": "score",
        "score": 0.0,
        "confidence": 1.0,
        "legend": {
          "0": "Not frustrated: positive, neutral or purely factual.",
          "1": "Mild: a minor gripe or slight disappointment, said calmly.",
          "2": "Clearly frustrated: annoyed or let down by a real problem.",
          "3": "Very frustrated: angry, feels cheated, or the problem ruined the experience.",
          "4": "Furious: hostile or emphatic language, demands a refund, or vows never to buy again."
        },
        "probabilities": {"0": 1.0, "1": 0.0, "2": 0.0, "3": 0.0, "4": 0.0}
      },
      "problem_category": {
        "type": "choice",
        "choice": "none",
        "confidence": 1.0,
        "probabilities": {
          "performance": 0.0,
          "general_dissatisfaction": 0.0,
          "cleaning_maintenance": 0.0,
          "assembly": 0.0,
          "none": 1.0,
          "shipping_delivery": 0.0,
          "ease_of_use": 0.0,
          "customer_service": 0.0,
          "safety": 0.0,
          "price_value": 0.0,
          "other": 0.0,
          "build_quality": 0.0,
          "size_capacity": 0.0
        }
      },
      "language": {
        "type": "choice",
        "choice": "english",
        "confidence": 1.0,
        "probabilities": {
          "italian": 0.0,
          "french": 0.0,
          "korean": 0.0,
          "afrikaans": 0.0,
          "japanese": 0.0,
          "german": 0.0,
          "spanish": 0.0,
          "arabic": 0.0,
          "swahili": 0.0,
          "english": 1.0,
          "portuguese": 0.0,
          "russian": 0.0,
          "dutch": 0.0,
          "chinese": 0.0,
          "other": 0.0,
          "hindi": 0.0
        }
      },
      "sentiment": {
        "type": "choice",
        "choice": "positive",
        "confidence": 1.0,
        "probabilities": {"positive": 1.0, "mixed": 0.0, "negative": 0.0, "neutral": 0.0}
      },
      "recommendation": {
        "type": "choice",
        "choice": "recommends",
        "confidence": 0.94,
        "probabilities": {"recommends": 0.96, "none": 0.04, "warns_against": 0.0}
      },
      "churn_risk": {"type": "noul", "noul": 0.01},
      "safety_concern": {"type": "noul", "noul": 0.01},
      "suggestion": {"type": "noul", "noul": 0.01},
      "competitor_mention": {"type": "noul", "noul": 0.05},
      "mentions__chefspride_stainless_steel_spatula_set": {"type": "noul", "noul": 0.01},
      "mentions__flipmaster_long_handle_fork": {"type": "noul", "noul": 0.01},
      "mentions__grillguard_heat_resistant_gloves": {"type": "noul", "noul": 0.01},
      "mentions__grillmaster_elite_tongs": {"type": "noul", "noul": 0.01},
      "mentions__heatshield_premium_grill_cover": {"type": "noul", "noul": 0.01},
      "mentions__tempcheck_digital_thermometer": {"type": "noul", "noul": 0.01},
      "mentions__cleanburn_pellets": {"type": "noul", "noul": 0.01},
      "mentions__flamestarter_natural_fire_lighter": {"type": "noul", "noul": 0.01},
      "mentions__seasonpro_bbq_rub_collection": {"type": "noul", "noul": 0.01},
      "mentions__smokering_premium_lump_charcoal": {"type": "noul", "noul": 0.01},
      "mentions__woodchips_hickory_smoking_chips": {"type": "noul", "noul": 0.01},
      "mentions__bbq_baron_pellet_smoker": {"type": "noul", "noul": 0.01},
      "mentions__backyard_king_compact_grill": {"type": "noul", "noul": 0.01},
      "mentions__firemaster_pro_3000_gas_grill": {"type": "noul", "noul": 0.94},
      "mentions__flameforge_electric_indoor_grill": {"type": "noul", "noul": 0.01},
      "mentions__smokechief_deluxe_charcoal_kettle": {"type": "noul", "noul": 0.01},
      "mentions__turbogrill_portable_gas": {"type": "noul", "noul": 0.01}
    },
    "usage": {"input_tokens": 2917, "output_tokens": 907}
  }
}

{
  "at": "2026-09-18T11:59:52.646+00:00",
  "sentence": {"review_key": "dd3ea70e9f3a", "sentence_index": 0},
  "request_id": "req_01a0b4632e67769599cb65a843ba5e85",
  "latency_ms": 632,
  "sent": {
    "state": {
      "task": "Classify one sentence from a customer review of a barbecue product.",
      "note": "Judge what the sentence itself says. The full review is context for resolving what 'it' or 'this' refers to.",
      "sentence": "Absolutely blown away by the FireMaster Pro 3000!",
      "sentence_position": "1 of 10",
      "review": {
        "product_reviewed": "FireMaster Pro 3000 Gas Grill",
        "product_category": "grills",
        "full_text": "Absolutely blown away by the FireMaster Pro 3000! Been grilling for over 20 years and this is hands down the best investment I've ever made. The temperature control is incredible - holds steady within 5 degrees of your target temp. The build quality is outstanding, heavy gauge steel that's going to last decades. Assembly was straightforward with clear instructions, took me about 3 hours working at a leisurely pace. The cooking space is generous, easily fits 12 burgers or a full rack of ribs with room to spare. Heat distribution is perfectly even - no more hot spots burning one side while the other stays raw. The side burner is powerful enough for serious searing, and the warming rack keeps everything at the perfect serving temperature. My neighbors are already asking to borrow it! Worth every penny and then some."
      }
    },
    "model": "jev-latest",
    "questions": "<elided: the same 26 questions as the first exchange>"
  },
  "received": {
    "model": "jev-1.13.0",
    "answers": {
      "frustration": {
        "type": "score",
        "score": 0.0,
        "confidence": 1.0,
        "legend": {
          "0": "Not frustrated: positive, neutral or purely factual.",
          "1": "Mild: a minor gripe or slight disappointment, said calmly.",
          "2": "Clearly frustrated: annoyed or let down by a real problem.",
          "3": "Very frustrated: angry, feels cheated, or the problem ruined the experience.",
          "4": "Furious: hostile or emphatic language, demands a refund, or vows never to buy again."
        },
        "probabilities": {"0": 1.0, "1": 0.0, "2": 0.0, "3": 0.0, "4": 0.0}
      },
      "problem_category": {
        "type": "choice",
        "choice": "none",
        "confidence": 1.0,
        "probabilities": {
          "general_dissatisfaction": 0.0,
          "other": 0.0,
          "customer_service": 0.0,
          "assembly": 0.0,
          "price_value": 0.0,
          "cleaning_maintenance": 0.0,
          "ease_of_use": 0.0,
          "safety": 0.0,
          "build_quality": 0.0,
          "shipping_delivery": 0.0,
          "size_capacity": 0.0,
          "performance": 0.0,
          "none": 1.0
        }
      },
      "language": {
        "type": "choice",
        "choice": "english",
        "confidence": 1.0,
        "probabilities": {
          "afrikaans": 0.0,
          "spanish": 0.0,
          "french": 0.0,
          "german": 0.0,
          "italian": 0.0,
          "korean": 0.0,
          "swahili": 0.0,
          "chinese": 0.0,
          "japanese": 0.0,
          "portuguese": 0.0,
          "english": 1.0,
          "russian": 0.0,
          "arabic": 0.0,
          "hindi": 0.0,
          "dutch": 0.0,
          "other": 0.0
        }
      },
      "sentiment": {
        "type": "choice",
        "choice": "positive",
        "confidence": 1.0,
        "probabilities": {"positive": 1.0, "neutral": 0.0, "negative": 0.0, "mixed": 0.0}
      },
      "recommendation": {
        "type": "choice",
        "choice": "none",
        "confidence": 0.46,
        "probabilities": {"warns_against": 0.0, "recommends": 0.36, "none": 0.64}
      },
      "churn_risk": {"type": "noul", "noul": 0.01},
      "safety_concern": {"type": "noul", "noul": 0.02},
      "suggestion": {"type": "noul", "noul": 0.01},
      "competitor_mention": {"type": "noul", "noul": 0.02},
      "mentions__chefspride_stainless_steel_spatula_set": {"type": "noul", "noul": 0.01},
      "mentions__flipmaster_long_handle_fork": {"type": "noul", "noul": 0.01},
      "mentions__grillguard_heat_resistant_gloves": {"type": "noul", "noul": 0.01},
      "mentions__grillmaster_elite_tongs": {"type": "noul", "noul": 0.01},
      "mentions__heatshield_premium_grill_cover": {"type": "noul", "noul": 0.01},
      "mentions__tempcheck_digital_thermometer": {"type": "noul", "noul": 0.01},
      "mentions__cleanburn_pellets": {"type": "noul", "noul": 0.01},
      "mentions__flamestarter_natural_fire_lighter": {"type": "noul", "noul": 0.01},
      "mentions__seasonpro_bbq_rub_collection": {"type": "noul", "noul": 0.01},
      "mentions__smokering_premium_lump_charcoal": {"type": "noul", "noul": 0.01},
      "mentions__woodchips_hickory_smoking_chips": {"type": "noul", "noul": 0.01},
      "mentions__bbq_baron_pellet_smoker": {"type": "noul", "noul": 0.01},
      "mentions__backyard_king_compact_grill": {"type": "noul", "noul": 0.01},
      "mentions__firemaster_pro_3000_gas_grill": {"type": "noul", "noul": 0.99},
      "mentions__flameforge_electric_indoor_grill": {"type": "noul", "noul": 0.01},
      "mentions__smokechief_deluxe_charcoal_kettle": {"type": "noul", "noul": 0.01},
      "mentions__turbogrill_portable_gas": {"type": "noul", "noul": 0.01}
    },
    "usage": {"input_tokens": 2909, "output_tokens": 905}
  }
}

Classified 2 in 0.6s; 0 failed.

Join the answers back onto every sentence (duplicated reviews pick up the same answers) and save the flat result.

In [8]:
classified = sentences.join(answers, on=KEY, how="left")
classified.drop("answers_json").write_parquet(OUTPUT / "sentences_classified.parquet")
classified.select(
    "product_name", "sentence", pl.col("frustration").round(2), "problem_category", "sentiment", "products_mentioned", "language"
).head(15)

shape: (15, 7)
┌─────────────────────────────────┬───────────────────────────────────────────────────────────────┬─────────────┬─────────────────────────┬───────────┬─────────────────────────────────────┬──────────┐
│ product_name                    ┆ sentence                                                      ┆ frustration ┆ problem_category        ┆ sentiment ┆ products_mentioned                  ┆ language │
│ ---                             ┆ ---                                                           ┆ ---         ┆ ---                     ┆ ---       ┆ ---                                 ┆ ---      │
│ str                             ┆ str                                                           ┆ f64         ┆ str                     ┆ str       ┆ list[str]                           ┆ str      │
╞═════════════════════════════════╪═══════════════════════════════════════════════════════════════╪═════════════╪═════════════════════════╪═══════════╪═════════════════════════════════════╪══════════╡
│ FireMaster Pro 3000 Gas Grill   ┆ Absolutely blown away by the FireMaster Pro 3000!             ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│ FireMaster Pro 3000 Gas Grill   ┆ Been grilling for over 20 years and this is hands down the    ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│                                 ┆ best investment I've ever made.                               ┆             ┆                         ┆           ┆                                     ┆          │
│ FireMaster Pro 3000 Gas Grill   ┆ The temperature control is incredible - holds steady within 5 ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│                                 ┆ degrees of your target temp.                                  ┆             ┆                         ┆           ┆                                     ┆          │
│ FireMaster Pro 3000 Gas Grill   ┆ The build quality is outstanding, heavy gauge steel that's    ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│                                 ┆ going to last decades.                                        ┆             ┆                         ┆           ┆                                     ┆          │
│ FireMaster Pro 3000 Gas Grill   ┆ Assembly was straightforward with clear instructions, took me ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│                                 ┆ about 3 hours working at a l…                                 ┆             ┆                         ┆           ┆                                     ┆          │
│ FireMaster Pro 3000 Gas Grill   ┆ The cooking space is generous, easily fits 12 burgers or a    ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│                                 ┆ full rack of ribs with room to …                              ┆             ┆                         ┆           ┆                                     ┆          │
│ FireMaster Pro 3000 Gas Grill   ┆ Heat distribution is perfectly even - no more hot spots       ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│                                 ┆ burning one side while the other s…                           ┆             ┆                         ┆           ┆                                     ┆          │
│ FireMaster Pro 3000 Gas Grill   ┆ The side burner is powerful enough for serious searing, and   ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│                                 ┆ the warming rack keeps everyth…                               ┆             ┆                         ┆           ┆                                     ┆          │
│ FireMaster Pro 3000 Gas Grill   ┆ My neighbors are already asking to borrow it!                 ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│ FireMaster Pro 3000 Gas Grill   ┆ Worth every penny and then some.                              ┆ 0.0         ┆ none                    ┆ positive  ┆ ["FireMaster Pro 3000 Gas Grill"]   ┆ english  │
│ GrillMaster Elite Tongs         ┆ Really disappointed with these tongs.                         ┆ 2.0         ┆ general_dissatisfaction ┆ negative  ┆ ["GrillMaster Elite Tongs"]         ┆ english  │
│ GrillMaster Elite Tongs         ┆ Handle broke after just 3 uses.                               ┆ 1.92        ┆ build_quality           ┆ negative  ┆ ["GrillMaster Elite Tongs"]         ┆ english  │
│ GrillMaster Elite Tongs         ┆ Cheap plastic that can't handle any real heat.                ┆ 2.15        ┆ build_quality           ┆ negative  ┆ ["GrillMaster Elite Tongs"]         ┆ english  │
│ GrillMaster Elite Tongs         ┆ Going back to my old set.                                     ┆ 1.48        ┆ none                    ┆ negative  ┆ []                                  ┆ english  │
│ SmokeRing Premium Lump Charcoal ┆ This charcoal lights quickly and burns clean with minimal     ┆ 0.0         ┆ none                    ┆ positive  ┆ ["SmokeRing Premium Lump Charcoal"] ┆ english  │
│                                 ┆ ash.                                                          ┆             ┆                         ┆           ┆                                     ┆          │
└─────────────────────────────────┴───────────────────────────────────────────────────────────────┴─────────────┴─────────────────────────┴───────────┴─────────────────────────────────────┴──────────┘

## 4. What the answers say

### Sanity check: does frustration track the star rating?

Jev never saw the rating, so if frustration falls as stars rise, it is reading the text rather than the number.

In [9]:
by_review = review_rollup(classified.lazy())
frustration_by_rating(by_review).collect()

shape: (5, 4)
┌────────┬─────────┬──────────────────┬──────────────────┐
│ rating ┆ reviews ┆ peak_frustration ┆ mean_frustration │
│ ---    ┆ ---     ┆ ---              ┆ ---              │
│ i64    ┆ u32     ┆ f64              ┆ f64              │
╞════════╪═════════╪══════════════════╪══════════════════╡
│ 1      ┆ 43      ┆ 3.01             ┆ 2.45             │
│ 2      ┆ 42      ┆ 1.93             ┆ 1.78             │
│ 3      ┆ 40      ┆ 1.16             ┆ 0.84             │
│ 4      ┆ 64      ┆ 0.74             ┆ 0.19             │
│ 5      ┆ 67      ┆ 0.03             ┆ 0.0              │
└────────┴─────────┴──────────────────┴──────────────────┘

### Which problems, for which products

In [10]:
problems = problems_by_product(classified.lazy()).collect()
problems.pivot("problem_category", index="product_name", values="sentences").fill_null(0).sort("product_name")

shape: (17, 13)
┌───────────────────┬─────────────┬───────────────┬─────────────┬───────────────────┬──────────────────┬─────────────┬───────────────┬──────────────────┬───────┬────────┬──────────────────┬──────────┐
│ product_name      ┆ performance ┆ build_quality ┆ ease_of_use ┆ general_dissatisf ┆ customer_service ┆ price_value ┆ size_capacity ┆ cleaning_mainten ┆ other ┆ safety ┆ shipping_deliver ┆ assembly │
│ ---               ┆ ---         ┆ ---           ┆ ---         ┆ action            ┆ ---              ┆ ---         ┆ ---           ┆ ance             ┆ ---   ┆ ---    ┆ y                ┆ ---      │
│ str               ┆ u32         ┆ u32           ┆ u32         ┆ ---               ┆ u32              ┆ u32         ┆ u32           ┆ ---              ┆ u32   ┆ u32    ┆ ---              ┆ u32      │
│                   ┆             ┆               ┆             ┆ u32               ┆                  ┆             ┆               ┆ u32              ┆       ┆        ┆ u32              ┆          │
╞═══════════════════╪═════════════╪═══════════════╪═════════════╪═══════════════════╪══════════════════╪═════════════╪═══════════════╪══════════════════╪═══════╪════════╪══════════════════╪══════════╡
│ BBQ Baron Pellet  ┆ 6           ┆ 1             ┆ 1           ┆ 1                 ┆ 0                ┆ 0           ┆ 7             ┆ 0                ┆ 0     ┆ 0      ┆ 0                ┆ 0        │
│ Smoker            ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ BackYard King     ┆ 24          ┆ 24            ┆ 0           ┆ 17                ┆ 13               ┆ 12          ┆ 0             ┆ 5                ┆ 0     ┆ 0      ┆ 3                ┆ 0        │
│ Compact Grill     ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ ChefsPride        ┆ 0           ┆ 1             ┆ 3           ┆ 0                 ┆ 0                ┆ 2           ┆ 0             ┆ 0                ┆ 0     ┆ 4      ┆ 0                ┆ 0        │
│ Stainless Steel   ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ Spatula Set       ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ CleanBurn Pellets ┆ 13          ┆ 0             ┆ 0           ┆ 0                 ┆ 0                ┆ 1           ┆ 0             ┆ 0                ┆ 0     ┆ 0      ┆ 0                ┆ 0        │
│ FireMaster Pro    ┆ 0           ┆ 0             ┆ 1           ┆ 0                 ┆ 0                ┆ 1           ┆ 0             ┆ 0                ┆ 0     ┆ 0      ┆ 0                ┆ 1        │
│ 3000 Gas Grill    ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ FlameForge        ┆ 28          ┆ 0             ┆ 0           ┆ 8                 ┆ 0                ┆ 4           ┆ 0             ┆ 0                ┆ 0     ┆ 0      ┆ 0                ┆ 0        │
│ Electric Indoor   ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ Grill             ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ FlameStarter      ┆ 14          ┆ 0             ┆ 0           ┆ 6                 ┆ 0                ┆ 0           ┆ 0             ┆ 0                ┆ 4     ┆ 4      ┆ 0                ┆ 0        │
│ Natural Fire      ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ Lighter           ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ FlipMaster Long   ┆ 0           ┆ 4             ┆ 7           ┆ 0                 ┆ 0                ┆ 4           ┆ 3             ┆ 4                ┆ 0     ┆ 0      ┆ 0                ┆ 0        │
│ Handle Fork       ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ GrillGuard Heat   ┆ 1           ┆ 0             ┆ 21          ┆ 0                 ┆ 1                ┆ 0           ┆ 7             ┆ 0                ┆ 0     ┆ 2      ┆ 0                ┆ 0        │
│ Resistant Gloves  ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ GrillMaster Elite ┆ 0           ┆ 9             ┆ 1           ┆ 3                 ┆ 1                ┆ 0           ┆ 0             ┆ 1                ┆ 0     ┆ 0      ┆ 0                ┆ 0        │
│ Tongs             ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ HeatShield        ┆ 0           ┆ 9             ┆ 4           ┆ 0                 ┆ 0                ┆ 1           ┆ 0             ┆ 0                ┆ 2     ┆ 0      ┆ 0                ┆ 0        │
│ Premium Grill     ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ Cover             ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ SeasonPro BBQ Rub ┆ 21          ┆ 0             ┆ 0           ┆ 0                 ┆ 0                ┆ 0           ┆ 0             ┆ 0                ┆ 0     ┆ 0      ┆ 2                ┆ 0        │
│ Collection        ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ SmokeChief Deluxe ┆ 0           ┆ 2             ┆ 0           ┆ 1                 ┆ 0                ┆ 1           ┆ 0             ┆ 2                ┆ 0     ┆ 0      ┆ 2                ┆ 1        │
│ Charcoal Kettle   ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ SmokeRing Premium ┆ 6           ┆ 0             ┆ 3           ┆ 0                 ┆ 0                ┆ 7           ┆ 2             ┆ 0                ┆ 0     ┆ 0      ┆ 0                ┆ 0        │
│ Lump Charcoal     ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ TempCheck Digital ┆ 12          ┆ 0             ┆ 6           ┆ 0                 ┆ 0                ┆ 4           ┆ 5             ┆ 0                ┆ 0     ┆ 0      ┆ 0                ┆ 0        │
│ Thermometer       ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ TurboGrill        ┆ 20          ┆ 12            ┆ 0           ┆ 5                 ┆ 0                ┆ 3           ┆ 0             ┆ 0                ┆ 0     ┆ 4      ┆ 0                ┆ 0        │
│ Portable Gas      ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
│ WoodChips Hickory ┆ 26          ┆ 6             ┆ 0           ┆ 0                 ┆ 0                ┆ 4           ┆ 2             ┆ 0                ┆ 0     ┆ 0      ┆ 0                ┆ 0        │
│ Smoking Chips     ┆             ┆               ┆             ┆                   ┆                  ┆             ┆               ┆                  ┆       ┆        ┆                  ┆          │
└───────────────────┴─────────────┴───────────────┴─────────────┴───────────────────┴──────────────────┴─────────────┴───────────────┴──────────────────┴───────┴────────┴──────────────────┴──────────┘

In [11]:
# The most frustrating problem areas, where at least 3 reviews raise them
problems.filter(pl.col("reviews") >= 3).sort("mean_frustration", descending=True).head(10)

shape: (10, 5)
┌──────────────────────────────────┬─────────────────────────┬───────────┬─────────┬──────────────────┐
│ product_name                     ┆ problem_category        ┆ sentences ┆ reviews ┆ mean_frustration │
│ ---                              ┆ ---                     ┆ ---       ┆ ---     ┆ ---              │
│ str                              ┆ str                     ┆ u32       ┆ u32     ┆ f64              │
╞══════════════════════════════════╪═════════════════════════╪═══════════╪═════════╪══════════════════╡
│ BackYard King Compact Grill      ┆ general_dissatisfaction ┆ 17        ┆ 12      ┆ 3.31             │
│ TurboGrill Portable Gas          ┆ general_dissatisfaction ┆ 5         ┆ 3       ┆ 3.13             │
│ BackYard King Compact Grill      ┆ customer_service        ┆ 13        ┆ 10      ┆ 3.0              │
│ FlameForge Electric Indoor Grill ┆ general_dissatisfaction ┆ 8         ┆ 6       ┆ 2.97             │
│ FlameForge Electric Indoor Grill ┆ price_value             ┆ 4         ┆ 4       ┆ 2.85             │
│ BackYard King Compact Grill      ┆ price_value             ┆ 12        ┆ 12      ┆ 2.71             │
│ TempCheck Digital Thermometer    ┆ price_value             ┆ 4         ┆ 4       ┆ 2.46             │
│ BackYard King Compact Grill      ┆ performance             ┆ 24        ┆ 18      ┆ 2.4              │
│ BackYard King Compact Grill      ┆ cleaning_maintenance    ┆ 5         ┆ 5       ┆ 2.31             │
│ BackYard King Compact Grill      ┆ build_quality           ┆ 24        ┆ 15      ┆ 2.24             │
└──────────────────────────────────┴─────────────────────────┴───────────┴─────────┴──────────────────┘

### Language

Every review in this sample is English, so this is a guard for when new data arrives rather than a finding.

In [12]:
classified.group_by("language").agg(pl.len(), pl.col("language_confidence").min().alias("min_confidence"))

shape: (1, 3)
┌──────────┬──────┬────────────────┐
│ language ┆ len  ┆ min_confidence │
│ ---      ┆ ---  ┆ ---            │
│ str      ┆ u32  ┆ f64            │
╞══════════╪══════╪════════════════╡
│ english  ┆ 1108 ┆ 1.0            │
└──────────┴──────┴────────────────┘

### Products mentioned in reviews of *other* products

Compatibility and bundling signals - e.g. a cover reviewed alongside the grill it fits.

In [13]:
cross_mentions(classified.lazy()).collect()

shape: (1, 3)
┌────────────────────────────────┬───────────────────────────────┬──────────────────────────────────────────────────────┐
│ product_name                   ┆ also_mentions                 ┆ sentence                                             │
│ ---                            ┆ ---                           ┆ ---                                                  │
│ str                            ┆ str                           ┆ str                                                  │
╞════════════════════════════════╪═══════════════════════════════╪══════════════════════════════════════════════════════╡
│ HeatShield Premium Grill Cover ┆ FireMaster Pro 3000 Gas Grill ┆ Solid grill cover that fits my FireMaster perfectly. │
└────────────────────────────────┴───────────────────────────────┴──────────────────────────────────────────────────────┘

### Escalations: safety concerns and churn risk

In [14]:
flagged(classified.lazy(), "safety_concern").collect()

shape: (17, 5)
┌────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────────┬─────────────┬─────────────┐
│ product_name                           ┆ sentence                                                                                    ┆ safety_concern ┆ occurrences ┆ frustration │
│ ---                                    ┆ ---                                                                                         ┆ ---            ┆ ---         ┆ ---         │
│ str                                    ┆ str                                                                                         ┆ f64            ┆ u32         ┆ f64         │
╞════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╪════════════════╪═════════════╪═════════════╡
│ GrillGuard Heat Resistant Gloves       ┆ Claimed to handle 932°F but my hands got burned picking up a moderately hot grate.          ┆ 0.97           ┆ 1           ┆ 2.52        │
│ TurboGrill Portable Gas                ┆ Gas connections leak.                                                                       ┆ 0.97           ┆ 2           ┆ 1.51        │
│ GrillGuard Heat Resistant Gloves       ┆ False advertising and dangerous.                                                            ┆ 0.92           ┆ 1           ┆ 3.24        │
│ ChefsPride Stainless Steel Spatula Set ┆ Handles get extremely hot and become uncomfortable to use.                                  ┆ 0.78           ┆ 1           ┆ 1.98        │
│ ChefsPride Stainless Steel Spatula Set ┆ Only complaint is the handles get quite hot during longer cooking sessions.                 ┆ 0.77           ┆ 2           ┆ 1.0         │
│ BackYard King Compact Grill            ┆ The temperature gauge is completely inaccurate, shows 300°F when it's clearly much hotter,… ┆ 0.76           ┆ 3           ┆ 2.99        │
│ TurboGrill Portable Gas                ┆ Legs are wobbly and the whole thing feels like it might tip over.                           ┆ 0.71           ┆ 2           ┆ 1.98        │
│ TempCheck Digital Thermometer          ┆ Shows 200°F when meat is clearly still raw, then jumps to 250°F instantly.                  ┆ 0.71           ┆ 2           ┆ 1.99        │
│ BackYard King Compact Grill            ┆ Temperature control doesn't work and the whole thing feels like it's about to collapse.     ┆ 0.7            ┆ 1           ┆ 2.78        │
│ TempCheck Digital Thermometer          ┆ Completely inaccurate thermometer.                                                          ┆ 0.64           ┆ 2           ┆ 2.38        │
│ GrillGuard Heat Resistant Gloves       ┆ Heat resistant gloves are a joke.                                                           ┆ 0.64           ┆ 1           ┆ 2.74        │
│ ChefsPride Stainless Steel Spatula Set ┆ Spatula set is decent quality but handles get quite hot during use.                         ┆ 0.64           ┆ 1           ┆ 1.01        │
│ ChefsPride Stainless Steel Spatula Set ┆ Would recommend getting some heat resistant gloves to go with them.                         ┆ 0.6            ┆ 2           ┆ 0.27        │
│ TempCheck Digital Thermometer          ┆ Tried calibrating multiple times but it's hopeless.                                         ┆ 0.53           ┆ 2           ┆ 2.18        │
│ BackYard King Compact Grill            ┆ Hot spots are severe and the ignition system is unreliable.                                 ┆ 0.52           ┆ 1           ┆ 2.02        │
│ BackYard King Compact Grill            ┆ Burner distribution is awful - one side barely lights while the other is a blowtorch.       ┆ 0.51           ┆ 2           ┆ 2.64        │
│ FlameStarter Natural Fire Lighter      ┆ Strong chemical smell that lingers on food.                                                 ┆ 0.51           ┆ 2           ┆ 2.0         │
└────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────────┴─────────────┴─────────────┘

In [15]:
flagged(classified.lazy(), "churn_risk").collect()

shape: (12, 5)
┌────────────────────────────────────────┬────────────────────────────────────────────────────────────────────┬────────────┬─────────────┬─────────────┐
│ product_name                           ┆ sentence                                                           ┆ churn_risk ┆ occurrences ┆ frustration │
│ ---                                    ┆ ---                                                                ┆ ---        ┆ ---         ┆ ---         │
│ str                                    ┆ str                                                                ┆ f64        ┆ u32         ┆ f64         │
╞════════════════════════════════════════╪════════════════════════════════════════════════════════════════════╪════════════╪═════════════╪═════════════╡
│ BackYard King Compact Grill            ┆ I'm returning it and will never buy from this company again.       ┆ 0.97       ┆ 3           ┆ 4.0         │
│ GrillMaster Elite Tongs                ┆ Going back to my old set.                                          ┆ 0.92       ┆ 3           ┆ 1.48        │
│ GrillGuard Heat Resistant Gloves       ┆ Returning immediately.                                             ┆ 0.92       ┆ 1           ┆ 2.59        │
│ GrillMaster Elite Tongs                ┆ Returning immediately.                                             ┆ 0.88       ┆ 1           ┆ 2.41        │
│ GrillGuard Heat Resistant Gloves       ┆ Prefer my old leather gloves.                                      ┆ 0.84       ┆ 2           ┆ 0.93        │
│ WoodChips Hickory Smoking Chips        ┆ Find a different supplier.                                         ┆ 0.78       ┆ 2           ┆ 2.63        │
│ TempCheck Digital Thermometer          ┆ Waste of money - get a different brand.                            ┆ 0.73       ┆ 1           ┆ 2.87        │
│ CleanBurn Pellets                      ┆ Find a better brand.                                               ┆ 0.73       ┆ 1           ┆ 2.27        │
│ WoodChips Hickory Smoking Chips        ┆ Get your chips elsewhere.                                          ┆ 0.72       ┆ 2           ┆ 2.58        │
│ ChefsPride Stainless Steel Spatula Set ┆ Save your money and buy quality tools elsewhere.                   ┆ 0.67       ┆ 1           ┆ 2.73        │
│ WoodChips Hickory Smoking Chips        ┆ Waste of money - get your chips from a reputable supplier instead. ┆ 0.67       ┆ 2           ┆ 2.91        │
│ BackYard King Compact Grill            ┆ Save yourself the headache and buy something else.                 ┆ 0.64       ┆ 2           ┆ 3.07        │
└────────────────────────────────────────┴────────────────────────────────────────────────────────────────────┴────────────┴─────────────┴─────────────┘

### Free product ideas: explicit suggestions

In [16]:
flagged(classified.lazy(), "suggestion").collect()

shape: (12, 5)
┌────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬─────────────┬─────────────┐
│ product_name                           ┆ sentence                                                                                    ┆ suggestion ┆ occurrences ┆ frustration │
│ ---                                    ┆ ---                                                                                         ┆ ---        ┆ ---         ┆ ---         │
│ str                                    ┆ str                                                                                         ┆ f64        ┆ u32         ┆ f64         │
╞════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╪════════════╪═════════════╪═════════════╡
│ HeatShield Premium Grill Cover         ┆ Only wish it came in different colors besides basic black.                                  ┆ 0.98       ┆ 2           ┆ 0.99        │
│ FlipMaster Long Handle Fork            ┆ Only wish the handle had better grip texture.                                               ┆ 0.96       ┆ 2           ┆ 1.0         │
│ BBQ Baron Pellet Smoker                ┆ Only complaint is the hopper could be larger for really long cooks.                         ┆ 0.95       ┆ 1           ┆ 1.0         │
│ TempCheck Digital Thermometer          ┆ Only complaint is the probe cables could be longer for larger grills.                       ┆ 0.95       ┆ 1           ┆ 1.0         │
│ TempCheck Digital Thermometer          ┆ Only downside is the probe cord could be longer for larger grills.                          ┆ 0.95       ┆ 2           ┆ 1.0         │
│ FlipMaster Long Handle Fork            ┆ Sturdy construction but the handle could be more comfortable for long cooking sessions.     ┆ 0.89       ┆ 2           ┆ 1.0         │
│ BBQ Baron Pellet Smoker                ┆ Hopper capacity could be larger for really long cooks but overall very satisfied with perf… ┆ 0.88       ┆ 2           ┆ 0.83        │
│ FlipMaster Long Handle Fork            ┆ Fork does the job but handle could be more comfortable.                                     ┆ 0.83       ┆ 1           ┆ 1.0         │
│ ChefsPride Stainless Steel Spatula Set ┆ Handles could be more comfortable but overall good value.                                   ┆ 0.8        ┆ 1           ┆ 0.95        │
│ GrillMaster Elite Tongs                ┆ Spring action could be smoother and the handles get warm during extended use.               ┆ 0.79       ┆ 1           ┆ 1.0         │
│ FireMaster Pro 3000 Gas Grill          ┆ Only minor gripe is the assembly instructions could be clearer - took me longer than expec… ┆ 0.68       ┆ 1           ┆ 1.0         │
│ SeasonPro BBQ Rub Collection           ┆ Packaging could be better as some of the containers leaked during shipping.                 ┆ 0.65       ┆ 2           ┆ 1.1         │
└────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴─────────────┴─────────────┘

### Competitors and previous products

In [17]:
flagged(classified.lazy(), "competitor_mention").collect()

shape: (11, 5)
┌──────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬─────────────┬─────────────┐
│ product_name                     ┆ sentence                                                                                    ┆ competitor_mention ┆ occurrences ┆ frustration │
│ ---                              ┆ ---                                                                                         ┆ ---                ┆ ---         ┆ ---         │
│ str                              ┆ str                                                                                         ┆ f64                ┆ u32         ┆ f64         │
╞══════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════╪════════════════════╪═════════════╪═════════════╡
│ GrillGuard Heat Resistant Gloves ┆ Prefer my old leather gloves.                                                               ┆ 0.94               ┆ 2           ┆ 0.93        │
│ GrillMaster Elite Tongs          ┆ Going back to my old set.                                                                   ┆ 0.92               ┆ 3           ┆ 1.48        │
│ GrillMaster Elite Tongs          ┆ After years of using cheap ones that broke or bent, these are a revelation.                 ┆ 0.8                ┆ 1           ┆ 0.14        │
│ CleanBurn Pellets                ┆ Doesn't impart much smoke taste compared to other brands I've tried.                        ┆ 0.68               ┆ 2           ┆ 1.01        │
│ GrillGuard Heat Resistant Gloves ┆ Heat protection is good but dexterity suffers.                                              ┆ 0.62               ┆ 2           ┆ 1.05        │
│ TempCheck Digital Thermometer    ┆ Waste of money - get a different brand.                                                     ┆ 0.62               ┆ 1           ┆ 2.87        │
│ SmokeRing Premium Lump Charcoal  ┆ Only downside is it burns a bit faster than some other brands so you go through it quicker… ┆ 0.61               ┆ 2           ┆ 1.0         │
│ GrillGuard Heat Resistant Gloves ┆ Gloves are bulky and make it hard to grip smaller items.                                    ┆ 0.53               ┆ 2           ┆ 1.28        │
│ SmokeRing Premium Lump Charcoal  ┆ Only downside is it burns faster than regular charcoal so you use more.                     ┆ 0.52               ┆ 1           ┆ 0.99        │
│ WoodChips Hickory Smoking Chips  ┆ Better chips available elsewhere.                                                           ┆ 0.52               ┆ 2           ┆ 1.27        │
│ SmokeRing Premium Lump Charcoal  ┆ Burns clean but nothing special compared to other premium brands at this price point.       ┆ 0.52               ┆ 1           ┆ 1.02        │
└──────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴─────────────┴─────────────┘

### Low confidence: route to a person

Jev returns a confidence with every Choice. Where it could not separate the problem categories, that is a signal to send the sentence for human review rather than trust the label.

In [18]:
needs_review(classified.lazy(), min_confidence=0.6).collect()

shape: (60, 4)
┌────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────┬─────────────────────────┬─────────────────────────────┐
│ product_name                           ┆ sentence                                                               ┆ problem_category        ┆ problem_category_confidence │
│ ---                                    ┆ ---                                                                    ┆ ---                     ┆ ---                         │
│ str                                    ┆ str                                                                    ┆ str                     ┆ f64                         │
╞════════════════════════════════════════╪════════════════════════════════════════════════════════════════════════╪═════════════════════════╪═════════════════════════════╡
│ FlameStarter Natural Fire Lighter      ┆ Works but there are better natural options available.                  ┆ other                   ┆ 0.21                        │
│ WoodChips Hickory Smoking Chips        ┆ Better chips available elsewhere.                                      ┆ performance             ┆ 0.23                        │
│ TempCheck Digital Thermometer          ┆ App could use some improvements but overall very satisfied.            ┆ none                    ┆ 0.3                         │
│ BBQ Baron Pellet Smoker                ┆ Pellet smoker works as advertised but WiFi connectivity is unreliable. ┆ performance             ┆ 0.3                         │
│ GrillGuard Heat Resistant Gloves       ┆ Returning immediately.                                                 ┆ customer_service        ┆ 0.31                        │
│ WoodChips Hickory Smoking Chips        ┆ Wood chips are full of dirt and bark.                                  ┆ performance             ┆ 0.35                        │
│ WoodChips Hickory Smoking Chips        ┆ Terrible wood chips full of dust and debris.                           ┆ build_quality           ┆ 0.36                        │
│ CleanBurn Pellets                      ┆ Inconsistent sizes cause feeding problems in my smoker.                ┆ performance             ┆ 0.37                        │
│ WoodChips Hickory Smoking Chips        ┆ Some pieces are too large while others are sawdust.                    ┆ size_capacity           ┆ 0.38                        │
│ CleanBurn Pellets                      ┆ Decent but not exceptional.                                            ┆ performance             ┆ 0.38                        │
│ GrillMaster Elite Tongs                ┆ Going back to my old set.                                              ┆ none                    ┆ 0.38                        │
│ WoodChips Hickory Smoking Chips        ┆ Poor quality control results in inconsistent pieces.                   ┆ build_quality           ┆ 0.39                        │
│ GrillMaster Elite Tongs                ┆ Decent starter tongs but you'll want to upgrade eventually.            ┆ none                    ┆ 0.4                         │
│ …                                      ┆ …                                                                      ┆ …                       ┆ …                           │
│ BackYard King Compact Grill            ┆ But that's not even the worst part.                                    ┆ none                    ┆ 0.55                        │
│ BackYard King Compact Grill            ┆ Save your money and buy anything else.                                 ┆ price_value             ┆ 0.55                        │
│ GrillGuard Heat Resistant Gloves       ┆ Prefer my old leather gloves.                                          ┆ ease_of_use             ┆ 0.57                        │
│ HeatShield Premium Grill Cover         ┆ Grill cover fits poorly and material feels cheap.                      ┆ build_quality           ┆ 0.57                        │
│ BackYard King Compact Grill            ┆ Avoid this brand completely - you've been warned!                      ┆ general_dissatisfaction ┆ 0.58                        │
│ SmokeChief Deluxe Charcoal Kettle      ┆ Assembly took about 90 minutes.                                        ┆ none                    ┆ 0.58                        │
│ CleanBurn Pellets                      ┆ Burns dirty with lots of ash.                                          ┆ performance             ┆ 0.58                        │
│ HeatShield Premium Grill Cover         ┆ Only wish it came in different colors besides basic black.             ┆ other                   ┆ 0.58                        │
│ ChefsPride Stainless Steel Spatula Set ┆ Handles get extremely hot and become uncomfortable to use.             ┆ safety                  ┆ 0.58                        │
│ BackYard King Compact Grill            ┆ Total waste of money!                                                  ┆ general_dissatisfaction ┆ 0.58                        │
│ BackYard King Compact Grill            ┆ Terrible quality control.                                              ┆ build_quality           ┆ 0.59                        │
│ FlameStarter Natural Fire Lighter      ┆ Better to just use newspaper and kindling.                             ┆ performance             ┆ 0.59                        │
└────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────┴─────────────────────────┴─────────────────────────────┘

### Most frustrated reviews

In [19]:
by_review.sort("peak_frustration", descending=True).select(
    "rating", "product_name", pl.col("peak_frustration").round(2), "problems", "churn_risk", "safety_concern", "review_text"
).unique("review_text", maintain_order=True).head(10).collect()

shape: (10, 7)
┌────────┬──────────────────────────────────┬──────────────────┬────────────────────────────────────────────────────┬────────────┬────────────────┬────────────────────────────────────────────────────┐
│ rating ┆ product_name                     ┆ peak_frustration ┆ problems                                           ┆ churn_risk ┆ safety_concern ┆ review_text                                        │
│ ---    ┆ ---                              ┆ ---              ┆ ---                                                ┆ ---        ┆ ---            ┆ ---                                                │
│ i64    ┆ str                              ┆ f64              ┆ list[str]                                          ┆ bool       ┆ bool           ┆ str                                                │
╞════════╪══════════════════════════════════╪══════════════════╪════════════════════════════════════════════════════╪════════════╪════════════════╪════════════════════════════════════════════════════╡
│ 1      ┆ BackYard King Compact Grill      ┆ 4.0              ┆ ["build_quality", "cleaning_maintenance", …        ┆ true       ┆ true           ┆ Total waste of money! This grill arrived with      │
│        ┆                                  ┆                  ┆ "shipping_delivery"]                               ┆            ┆                ┆ multiple dents and scratches, clearly damage…      │
│ 1      ┆ BackYard King Compact Grill      ┆ 3.91             ┆ ["build_quality", "general_dissatisfaction",       ┆ false      ┆ false          ┆ Worst grill purchase ever made. Everything about   │
│        ┆                                  ┆                  ┆ "performance"]                                     ┆            ┆                ┆ this BackYard King is cheap and poorly de…         │
│ 1      ┆ BackYard King Compact Grill      ┆ 3.62             ┆ ["customer_service", "general_dissatisfaction", …  ┆ false      ┆ false          ┆ Absolutely terrible grill with major design flaws. │
│        ┆                                  ┆                  ┆ "price_value"]                                     ┆            ┆                ┆ Temperature control doesn't work, heat …           │
│ 1      ┆ BackYard King Compact Grill      ┆ 3.59             ┆ ["build_quality", "cleaning_maintenance", …        ┆ false      ┆ false          ┆ Worst grill ever made. Everything about it is      │
│        ┆                                  ┆                  ┆ "price_value"]                                     ┆            ┆                ┆ cheap and poorly designed. The temperature k…      │
│ 1      ┆ TurboGrill Portable Gas          ┆ 3.51             ┆ ["build_quality", "general_dissatisfaction",       ┆ false      ┆ true           ┆ Portable grill is a disaster. Ignition system      │
│        ┆                                  ┆                  ┆ "safety"]                                          ┆            ┆                ┆ failed on the second use. Gas connections le…      │
│ 1      ┆ BackYard King Compact Grill      ┆ 3.36             ┆ ["build_quality", "general_dissatisfaction",       ┆ false      ┆ true           ┆ This grill is a complete disaster. Poor quality    │
│        ┆                                  ┆                  ┆ "performance"]                                     ┆            ┆                ┆ materials, terrible design, and non-existe…        │
│ 1      ┆ GrillGuard Heat Resistant Gloves ┆ 3.24             ┆ ["customer_service", "performance", "safety"]      ┆ true       ┆ true           ┆ Heat resistant gloves are a joke. Claimed to       │
│        ┆                                  ┆                  ┆                                                    ┆            ┆                ┆ handle 932°F but my hands got burned picking …     │
│ 1      ┆ GrillMaster Elite Tongs          ┆ 3.17             ┆ ["build_quality", "customer_service"]              ┆ true       ┆ false          ┆ Tongs broke on first use. Spring mechanism failed  │
│        ┆                                  ┆                  ┆                                                    ┆            ┆                ┆ and one handle cracked. Completely unacc…          │
│ 1      ┆ BackYard King Compact Grill      ┆ 3.07             ┆ ["build_quality", "customer_service",              ┆ true       ┆ true           ┆ Terrible quality control. Grill arrived with       │
│        ┆                                  ┆                  ┆ "performance"]                                     ┆            ┆                ┆ uneven legs so it wobbles constantly. Burner …     │
│ 1      ┆ FlameForge Electric Indoor Grill ┆ 3.07             ┆ ["general_dissatisfaction", "performance"]         ┆ false      ┆ false          ┆ Electric grill is useless. Takes 30 minutes to     │
│        ┆                                  ┆                  ┆                                                    ┆            ┆                ┆ heat up and even then doesn't get hot enoug…       │
└────────┴──────────────────────────────────┴──────────────────┴────────────────────────────────────────────────────┴────────────┴────────────────┴────────────────────────────────────────────────────┘